### ISSUE TITLE
Audio does not seem to work

### ISSUE THREAD

**Issue by kaoskeya** [sskodje/ScreenRecorderLib#1]
Hey, very good work. I got the video recording as per the code in the README file. When I tried the sample for audio recording along with the video, does not seem to work. `AudioOptions` does not seem to have an option to pass a device either.

Also, I see this is a new project. Anyway pointers on how we can contribute?

**Comment by sskodje** [comment]
Hello! You are correct that it's a new project, and in no means complete. I made this library as a part of another project, basically learning as i go. Selecting audio device is one of the features that is not yet implemented, as you have found out.

It would be wonderful if you want to contribute! If you fix or add something, don't be afraid to make a pull request. I've been meaning to write up a list of stuff that needs to be fixed.

**Comment by sskodje** [comment]
I've split this out into two separate issues. I'd love some more info on your sound setup to figure out why the default system sound capture doesn't work.

**Comment by sskodje** [comment]
Implemented with d5d95cf94212a5ebc30465c82e09fe786d17a06e
