### ISSUE TITLE
Error: The application requested an operation that relies on an SDK component that does not exist or does not match.

### ISSUE THREAD

**Issue by npilarca** [sskodje/ScreenRecorderLib#100]
I tried running the sample application in VS2019, but I keep getting the error in the attached image. It's in Japanese, but the title literally translates it. Am I missing an SDK or something to install? I can't seem to get it to run.

![image](https://user-images.githubusercontent.com/73165094/96563459-ef40ec00-12fc-11eb-8c42-b8a2c4c3cf95.png)

**Comment by sskodje** [comment]
Hello! In some cases this problem can be due to having a Windows without "media features" installed, the so called "Windows N" version. Do you have Windows Media Player installed? If not, there is a good change it is an "N" version. You can download the feature here: https://www.microsoft.com/en-us/software-download/mediafeaturepack

**Comment by npilarca** [comment]
Yes I have Windows Media Player installed. My computer is also Windows 10 Enterprise, I don't think it's a "Windows N" Version.

**Comment by npilarca** [comment]
Is there anything I missed to have installed? I just tried to run the sample application directly

**Comment by sskodje** [comment]
There are no other dependencies than Media Foundation which is bundled with windows (or in the media feature pack), and Visual C++ runtime. The only thing i can think of is that there is something going on with the graphics driver. Does it work if you disable hardware encoding?

**Comment by npilarca** [comment]
I tried just building a simple application from the NuGet and that worked great. I couldn't figure out what was happening with the sample application, I also tried disabling hardware encoding but it still wouldn't work. Thank you for the help though!

**Comment by npilarca** [comment]
On an unrelated question, is there any function within the package that could support recording of a specific window instead of the entire screen?

**Comment by sskodje** [comment]
I'm working on it for the next release.
