### ISSUE TITLE
Error: The Parameter is incorrect

### ISSUE THREAD

**Issue by drewbuckley** [sskodje/ScreenRecorderLib#101]
Hi and thanks for the library.

A strange thing. The Test app works perfectly to record on my PC however when i copy the Record code with Config over to my app i get Rec_OnRecordingFailed with "The Parameter is incorrect". Everything appears to be the same but obviously not.

I've checked all the config in the test app which works to the values in my app and they're the same. I've checked that .NET Framework is 4.5.2 on both and using the 32bit DLL on both.

Tried commenting out the RETURN_ON_BAD_HR as found in a simlar thread but no change.

Any help would be greatly appreciated. At a loss here.

**Comment by sskodje** [comment]
That's weird. Does it work with the Nuget package?

**Comment by drewbuckley** [comment]
Thanks sskodje for getting back.

Same thing with Nuget, the DLL from here and also adding the C++ project in Visual Studio. Obviously something different in my environment than the Test but can't seem to find what that would be and the error message doesn't tell me much. Same in the Log.txt.

**Comment by drewbuckley** [comment]
I did manage to find this. 

  | Name | Value | Type
-- | -- | -- | --
▶ | *_rec.lRec | '*_rec.lRec' threw an exception of type 'System.NullReferenceException' | internal_recorder {System.NullReferenceException}

Doesn't make any sense how the same code outside of my application is fine but inside it's not.

**Comment by drewbuckley** [comment]
I found that my app already had a lock on the DesktopDuplication for other things. Removing that fixed it. Interesting.

Thanks
