### ISSUE TITLE
Record in timed segments

### ISSUE THREAD

**Issue by asim-rehman** [sskodje/ScreenRecorderLib#102]
Is it possible to split the video recording into X minute clips? Looking at options, seems there is no built in option and current work around would be to add a timer and create a new recorder every time with same recorder options.

Is there a better way of accomplishing this?

**Comment by sskodje** [comment]
No that is not possible. You either need to loop it as you said, or use some command line tool to split it after the fact, like ffmpeg.

**Comment by kasirajansfm** [comment]
am using loop to record every minute video, but am unable to stop the previous recording.
