### ISSUE TITLE
Exception while running Winform Application with 3.0.1 nudget package with VS2019

### ISSUE THREAD

**Issue by anunay1** [sskodje/ScreenRecorderLib#109]
Hi 

I am getting the below exception when I run my winform application: 

![image](https://user-images.githubusercontent.com/7989610/100436631-9b78ae00-30c5-11eb-91dc-bc0525668eda.png)

**Comment by sskodje** [comment]
Hey! This error usually means that the application is trying to load a 64 bit DLL when running as 32 bit. I would make sure that there is no platform mismatch in your project configuration manager.  Remember that you cannot use "any cpu", your project has be either x86 or x64.

**Comment by antonywusz** [comment]
I met the same problem as above in VS2019 when selecting "Any CPU".

error : ScreenRecorderLib does not work correctly on 'AnyCPU' platform. You need to specify platform (x86, Win32 or x64).
