### ISSUE TITLE
After AcquireNextFrame , need to check DXGI_ERROR_INVALID_CALL

### ISSUE THREAD

**Issue by YongbeomBahg** [sskodje/ScreenRecorderLib#114]
I found 2.5.0 version CHECKED return value of AcquireNextFrame  for DXGI_ERROR_INVALID_CALL
but current 3.0.2 version  doen't have this and it might return with error and quit recording
You are able to reproduce it with Windows+L while recording

**Comment by sskodje** [comment]
Hmm, yes it does indeed happen intermittently. It's undocumented, but it doesn't seem to be harmful to retry when it happens. I'll make some changes to accomodate for it.

**Comment by sskodje** [comment]
Fixed with ac9789bfeba2481416270bcf26e389f12a0f8968
