### ISSUE TITLE
Recording multiple screens at once

### ISSUE THREAD

**Issue by m6t** [sskodje/ScreenRecorderLib#115]
I do not seem to be able to record multiple screens at the same time. Is this could be done? If it is, how? 

Passing screen coordinates that includes both of them do not seem to work

This is what i tried 

`           
var minx = Screen.AllScreens.Min(x => x.Bounds.X);
var miny = Screen.AllScreens.Min(x => x.Bounds.Y);

var maxx = Screen.AllScreens.Max(x => x.Bounds.X + x.Bounds.Width);
var maxy = Screen.AllScreens.Max(x => x.Bounds.Y + x.Bounds.Height);

var totalWidth = maxx - minx;
var totalHeight = maxy - miny;

var CaptureRectangle = new System.Drawing.Rectangle(minx, miny, totalWidth, totalHeight);

....

DisplayOptions = new DisplayOptions()
{
    Top = CaptureRectangle.Top,
    Left = CaptureRectangle.Left,
    Bottom = CaptureRectangle.Bottom,
    Right = CaptureRectangle.Right
}

....

`

Captrue rectangle values are 
![image](https://user-images.githubusercontent.com/12183136/106571143-d7a61000-6547-11eb-9435-a13dc899d4d8.png)

**Comment by sskodje** [comment]
It's not supported yet, i'm working on it for a future release.

**Comment by m6t** [comment]
I tried creating a Winforms window and making it transparent to all click events and setting it as topmost. After that i passed the handle of the window to DisplayOptions and started recording that. I have a timer in this window and it uses Graphics.CopyFromScreen to copy screen content to a bitmap. then i show the bitmap on a PictureBox in the window. So i am recording the picturebox which contains the whole virtual screen area.

But there is a problem in this approach.

Graphics.CopyFromScreen throws weird errors after 1800 ~ 1900 calls. I am disposing all the graphics objects and bitmaps that is not a problem. I also tried AForge.Video.ScreenCaptureStream to grab the frames but the same error was thrown in the AForge liblary.

-----------------------

Does this new version has some kind of demo or some code that i can try to implement or copy from.

**Comment by sskodje** [comment]
I believe this is fixed with 15e911926cf0747389aeea5b06185a1618831f84, as there was a memory leak issue.

**Comment by m6t** [comment]
Leak is not in your code. Graphics.CopyFromScreen was the problem as i used it to captrue multiple screens and pass it to recorder. [take a look at this issue](https://social.msdn.microsoft.com/Forums/vstudio/en-US/cedaa0f2-383c-4e61-92c0-c09123cb67cd/need-help-confirming-possible-bug-in-graphicscopyfromscreen-regarding-leakage-of-gdi-object-handle?forum=netfxbcl)

**Comment by sskodje** [comment]
Ah right. I can't really provide any help with code outside this project. 

You can check out this branch, which is my work in progress. It should compile, but it is not tested and not complete.

https://github.com/sskodje/ScreenRecorderLib/tree/multimonitor_recording

**Comment by coxy24** [comment]
> It's not supported yet, i'm working on it for a future release.

Hi sskodje

First of thanks for this package and the time you put into it, I find it really useful. 

I was just wondering if you have had any luck with this feature ?

**Comment by sskodje** [comment]
It's a work in progress. You can check out [this branch](https://github.com/sskodje/ScreenRecorderLib/tree/multimonitor_recording) if you want to test it. It should be pretty feature complete, but there are some known bugs related to especially laptops with integrated + discrete graphics i haven't ironed out yet.

**Comment by sskodje** [comment]
Added in 83202d6490ba66d1bba21f0f94e9a7e25449dbe8
