### ISSUE TITLE
Recording is not happening when capture by application window

### ISSUE THREAD

**Issue by athiemailid** [sskodje/ScreenRecorderLib#116]
Hi,

I have tried application window capture with take snapshot with video by using latest version 3.1.0.  After 10 minutes, recording is not happening and application was hanged.  Video file is not generated as well.  You can reproduce the issue by configuring the same option as per the sample screenshot. Also I have attached the log file for your reference. 
**### Note : Capture application windows recording worked well in 3.0.2 version.**
[log.txt](https://github.com/sskodje/ScreenRecorderLib/files/5923212/log.txt)
![snopshot](https://user-images.githubusercontent.com/60776018/106845425-40c78800-66ee-11eb-9600-7a0ee9b938f4.png)

**Comment by sskodje** [comment]
Thanks, i reproduced it. I think it's a memory leak.

**Comment by sskodje** [comment]
Fixed with 15e911926cf0747389aeea5b06185a1618831f84

**Comment by athiemailid** [comment]
Thanks for fixing this issue.
