### ISSUE TITLE
Camera Support

### ISSUE THREAD

**Issue by rashad-farajullayev** [sskodje/ScreenRecorderLib#117]
Thanks for this great library.

I need to have some possibility to add to a corner of a resulting video video capture from camera. So that the one who takes the screencast recorded not only the desktop but also himself. And probably in the RecordingOptions have some setting to specify size and location of the camera capture.

**Comment by rashad-farajullayev** [comment]
Dear Author - ssodje. 
How do I help you to implement it asap? This feature needed very urgently in my project. How can we communicate?
I cannot yet open this solution in Visual Studio and compile it. Would you please give short intro on how to prepare its development environment and how to run it? I used C++ many years ago, but still remember to add enhancements to this code.

**Comment by sskodje** [comment]
It should to my knowledge not require more than Visual Studio 2019 with "Desktop development with C++" enabled in Visual Studio Installer.

I'm in the process of a rewrite to support multimonitor recording however, so it's a bit of an awkward moment to introduce changes on the current main branch. I'll probably release and merge into master some time this week, and then i'll make a branch for this feature.

**Comment by rashad-farajullayev** [comment]
hello @sskodje , 
any news on the screen recorder feature?

**Comment by sskodje** [comment]
I'm working on adding it for next release, soon™.

**Comment by rashad-farajullayev** [comment]
Hi @sskodje I was not able to compile this solution and implement camera support.
Have you done anything? Are there any news with it?
I have written OpenCV interaction and I can grab frames from default system camera. If there were any possibility to somehow overlay custom bitmaps on the screenshot before writing them to video output, I could add that overlay by myself

**Comment by sskodje** [comment]
Added in 83202d6490ba66d1bba21f0f94e9a7e25449dbe8
