### ISSUE TITLE
Snapshots are not created when starts recording to FileStream

### ISSUE THREAD

**Issue by name1ess0ne** [sskodje/ScreenRecorderLib#118]
Hello, thanks for an amazing library!

I have noticed that it is impossible to create snapshots when I use `FileStream` in `recorder.Record` method.
In code below snapshots aren't created:

```c#
RecorderOptions options = new RecorderOptions();
options.VideoOptions = new VideoOptions 
{ 
    SnapshotsWithVideo = true, 
    SnapshotsInterval = 2, 
    SnapshotFormat = ImageFormat.JPEG 
};

using (var rec = Recorder.CreateRecorder(options))
using (var fileStream = new FileStream(filePath, FileMode.Create))
{
    rec.Record(fileStream);//Snapshots will not be created with FileStreams
}
```

And everything works just fine with this code:
```c#
RecorderOptions options = new RecorderOptions();
options.VideoOptions = new VideoOptions 
{ 
    SnapshotsWithVideo = true, 
    SnapshotsInterval = 2, 
    SnapshotFormat = ImageFormat.JPEG 
};

using (var rec = Recorder.CreateRecorder(options))
{
    rec.Record(filePath);//here the file path is specified instead of a stream
}
```

Seems, in case of `FileStream` recorder doesn't know destination path for snapshots, but it doesn't throw any exception. Snapshots just aren't created. 
Maybe it is possible to have additional setting for directory where to save snapshots?
Thanks!

**Comment by sskodje** [comment]
That's indeed a bug yeah, as you said, it does not know where to store the snapshots. A setting to configure a directory sounds like a good fix. 

Thanks for reporting it 👍

**Comment by sskodje** [comment]
Support for snapshot directories added with 83202d6490ba66d1bba21f0f94e9a7e25449dbe8
