### ISSUE TITLE
Unspecified Error

### ISSUE THREAD

**Issue by m6t** [sskodje/ScreenRecorderLib#119]
Hi, we are getting Unspecified Error when we start the recording. I cannot reproduce it in any other machine. I know this liblary is not to blame and there is something diffrent about the machine but i cant figure out what. How can i get more detailed error for this issue? 

Unspecified Error comes from the RecordingFailed event.

**Comment by sskodje** [comment]
The usual suspect is that windows is missing media features. I'll see if i can add a better error for when this happens.

 https://www.microsoft.com/en-us/software-download/mediafeaturepack

**Comment by m6t** [comment]
Thanks for quick reply, the media feature pack installer says the update is not applicable to your computer. Is this means it allready exists or that it cant be installed to this machine

**Comment by sskodje** [comment]
Ah right. Another issue could be that it is missing the [C++ runtime](https://www.microsoft.com/en-us/download/details.aspx?id=48145)

**Comment by m6t** [comment]
Unfortunately that was not the issue. I've checked the Event Viewer too but nothing was there 😢

**Comment by sskodje** [comment]
It might be a dumb question, but have you tried installing windows update and restarting the machine? I've had experience in the past that Windows Update can start installing, and when it is in "pending restart" mode, some of the windows API's don't work.

**Comment by m6t** [comment]
Unfortunately that's not an option 🙄. Its a bank machine which is not allowed to be updated. We have restarted the machine several times during installing c++ runtime. I think the windows api might be restricted for use in bank policies but expression encoder works fine on the machine. And skype is able to share screen which seems to be using the same api with your code. And the bank doesn't give us any information about their security policy so we really don't know. EventViewer seems clean I think there would be some entries if it is a security issue.

**Comment by sskodje** [comment]
Right. The problem i mentioned is only on machines with pending updates installing, so if the machine can't update, there can't be any problems eithre.

You can enable logging in release by using the IsLogEnabled, LogSeverityLevel and LogFilePath properties on RecorderOptions, perhaps that can shed some more light on the problem.

**Comment by m6t** [comment]
Hello again and thanks again for your help :)

I,ve gathered logs from the problematic machine but i couldnt understand the log. Does this show us anything new?

2021-02-25 14:03:40.574 [DEBUG] [internal_recorder.cpp(ConfigureOutputDir:184)] >> output folder is ready
2021-02-25 14:03:40.580 [INFO]  [internal_recorder.cpp(operator ():253)] >> Starting recording task
2021-02-25 14:03:40.841 [DEBUG] [internal_recorder.cpp(operator ():265)] >> Changed Recording Status to Recording
2021-02-25 14:03:40.842 [DEBUG] [internal_recorder.cpp(CleanupResourcesAndShutDownMF:372)] >> Released IMFSinkWriter
2021-02-25 14:03:40.842 [DEBUG] [internal_recorder.cpp(CleanupResourcesAndShutDownMF:374)] >> Released ID3D11DeviceContext
2021-02-25 14:03:40.846 [DEBUG] [internal_recorder.cpp(CleanupResourcesAndShutDownMF:376)] >> Released ID3D11Device
2021-02-25 14:03:40.848 [INFO]  [internal_recorder.cpp(CleanupResourcesAndShutDownMF:387)] >> Media Foundation shut down
2021-02-25 14:03:40.848 [ERROR] [internal_recorder.cpp(operator ():296)] >> Exception in RecordTask
2021-02-25 14:03:40.849 [DEBUG] [internal_recorder.cpp(SetRecordingCompleteStatus:401)] >> Changed Recording Status to Idle
2021-02-25 14:03:40.852 [DEBUG] [internal_recorder.cpp(SetRecordingCompleteStatus:423)] >> Sent Recording Failed callback

**Comment by sskodje** [comment]
It's actually the lack of any log output that is most surprising. Are you using the latest version? The next method it should have run should begin with printing a debug line on Desktop Duplication, and checking if the API is supported on Windows Graphics Capture, meaning the only thing that can crash is the GraphicsCaptureSession::IsSupported() function, which would be surprising.

**Comment by m6t** [comment]
Currently i use the 3.1.0.0 version and I use WindowsGraphicsCapture option. If there is a diffrence i can gather log from 3.1.1.0 version too. I guess WindowsGraphicsCapture is not supported than on the machine but instead of returning false it throws an error.

**Comment by m6t** [comment]
I feel like an idiot. It clearly states that WindowsGraphicsCapture is supported on win10 version 1803 or newer. Customer win10 version is 1709. I will try DesktopDuplication next and let you know and if it works i will close the issue.

But I think we found that IsSupported causes an error if winver is 1709 which is good to know.

**Comment by sskodje** [comment]
It seems one must also check for the presence of the API at all, before checking if it is available, so the error was in my code. It's not always easy working with Windows APIs.

**Comment by m6t** [comment]
Yea i myself have a lot of trouble in past weeks only with Windows APIs. 
Thank you for all your help, switching to DesktopDuplication fixed the issue and thanks for the library.

**Comment by m6t** [comment]
I closed this but 

> It seems one must also check for the presence of the API at all

 this seems worth keeping the issue up so im opening it again

**Comment by sskodje** [comment]
Fixed with 83202d6490ba66d1bba21f0f94e9a7e25449dbe8
