### ISSUE TITLE
Records shorter than 15min?

### ISSUE THREAD

**Issue by richardli7** [sskodje/ScreenRecorderLib#12]
Hi there.

Thanks for the great tool, I recorded a lot of my program running videos.

There is a small puzzle for me that it seems my recordings could not last capturing for more than 15min. Is it me using it wrong or it is a feature?

I currently work that around by dividing between steps:
![image](https://user-images.githubusercontent.com/20408106/39156106-dd992868-47a8-11e8-8bee-048a4506f097.png)

Has anyone managed to record a longer clip like 1 hour or 2?

Cheers,
Richard

**Comment by sskodje** [comment]
Hey!

There is indeed an issue that causes memory usage to grow, if the system is not powerful enough to encode in real time.  I'll look into it the next couple days.

**Comment by Cuningan** [comment]
But is a memory leak or simply that grows because it is working?

**Comment by sskodje** [comment]
Frames are queued to be encoded, and if you are recording 60 frames per second, but the encoder is only able to encode 50, you're going to add 10 frames to memory every second. Eventually the videoram fills up, it starts to swap to system memory, cpu useage spikes, and the whole ting becomes a crawl.

**Comment by sskodje** [comment]
I've discovered the issue is with dynamic framerate only. It seems the act of requesting a frame from the desktop duplication API is locking something that prevents the video encoder to process frames. Interestingly enough, that means that the less screen updates there are, like a desktop, the slower the encoder processes video, while recording something like a game or a video at 60 fps makes it work faster.

A simple workaround seems to be to just enable fixed framerate in VideoOptions, and the problem goes away. I'll dig more at this problem..

**Comment by richardli7** [comment]
Thanks for your comments, I checked with my code, I think it is on fixed rate,already. I will tune further down the settings and try.
![image](https://user-images.githubusercontent.com/20408106/39275475-820d3dd0-4939-11e8-80a5-3839d59f52e6.png)


By the way, it seems something might have gone wrong after I switched from 1.0.8 to 1.1.0 to fix the Console output spam. I will switch to 1.0.9 and see.
![image](https://user-images.githubusercontent.com/20408106/39275454-70549070-4939-11e8-91d0-1c230747b133.png)

Cheers.

**Comment by sskodje** [comment]
Hmm ok. You have very modest settings, so it _should_ work without a hitch. Can you check if hardware acceleration is working? Easiest way is to check task manager-> performance and see if GPU is active while recording.

Do you get any errors on the 0kb files? I cannot reproduce it.

**Comment by richardli7** [comment]
> Do you get any errors or debug console output on the 0kb files? I cannot reproduce it. Thanks for helping debug btw :)

No,  I tried again today, because the console spam is gone as I was using the latest version of 1.1.0, I did not see any message saying error or abnormal.

I think the 0kb does not exist in 1.0.9 , so comparing two versions may gain some ideas.
I will try to have a compare between these two versions.

**Comment by sskodje** [comment]
I see. The debug output should be visible in the Visual Studio debug console still btw. I will have a look at the changes in 1.10.

**Comment by richardli7** [comment]
Hi sskodje, I tried with Visual Studio debug console today to reproduce the 0kb files issue in version 1.1.0.  It did not show anything abnormal from Debug console output but only 0kb files.

I will do a code clean and hand you a demo project soon.

Cheers,
Richard

**Comment by sskodje** [comment]
I indentified several issues in the code that i believe is related to your problems, and released a new version with fixes. The problems were related to uninitialized variables in some scenarios creating undefined behavior, missing error handling, and a throttling issue in the sink writer.

I hope this fixes your problems, and i want to thank you again for helping me find these problems.

**Comment by richardli7** [comment]
Don't mention that, thank you for developing this great tool!

You were fast resolving this, I can see how good you are in this area.

I will get a later version and try soon. Thanks again!
