### ISSUE TITLE
Stutter when CPU is busy.

### ISSUE THREAD

**Issue by aqibbanday** [sskodje/ScreenRecorderLib#124]
I used CPU-Z bench/stress test when recording a video, had a lot of stutter during that period.
https://www.cpuid.com/downloads/cpu-z/cpu-z_1.95-en.exe
You can use this to stress CPU under bench tab click stress while recording.

**Comment by aqibbanday** [comment]
@sskodje is this fixed?

**Comment by sskodje** [comment]
I have made many performance improvements, and the library is as performant as i can make it. It will never be immune to a busy cpu however.
