### ISSUE TITLE
[Questions] How to make screen screenshots easy

### ISSUE THREAD

**Issue by SID9-HoneyBee** [sskodje/ScreenRecorderLib#128]
I think it's a really great library.
It was easy to implement through samples, and in fact, it was possible to record video in high quality without consuming a lot of computer resources.

I am developing a project to share screens in real time.

For real-time screen sharing, continuous screen shots must be taken in the form of a Bitmap.

I would like a simple approach using this library.

Would you like to apply SnapShot from the sample project?

If you simply ScreenCopy the screen
It consumes a lot of resources with real-time response.

Can you tell me how to efficiently produce Bitmap in real time?

**Comment by rmayer92** [comment]
+1
