### ISSUE TITLE
Add overlay causes lag in multimonitor branch

### ISSUE THREAD

**Issue by aqibbanday** [sskodje/ScreenRecorderLib#130]
@sskodje multimonitor

**Comment by sskodje** [comment]
Thanks for the feedback, but can you be a bit more descriptive? What lags? Which overlay?

**Comment by aqibbanday** [comment]
I was testing the overlay feature, when i enabled all the overlays, like gif, image, webcam there was lag, then i tried it with only webcam the lag was still there.
It works fine without the overlay.

**Comment by sskodje** [comment]
And by lag you mean the recording was choppy, or that your PC lagged? Is the problem there with only say image overlay?

**Comment by aqibbanday** [comment]
Enabling only image overly works fine.
It seems its happening in GraphicsCaptureApi and sometimes crashes when recording is stopped.

**Comment by aqibbanday** [comment]
I am testing with YouTube video and the video becomes choppy.

**Comment by sskodje** [comment]
Thanks, i'll check it out.

**Comment by aqibbanday** [comment]
Ok.

**Comment by sskodje** [comment]
I'm not able to reproduce unfortunately. If you recording with the "log to file" option and "Trace" logging enabled in the test app and upload the log here, i can perhaps identify the issue.

**Comment by aqibbanday** [comment]
Sure.

**Comment by aqibbanday** [comment]
[log.txt](https://github.com/sskodje/ScreenRecorderLib/files/6265119/log.txt)

**Comment by aqibbanday** [comment]
[log.txt](https://github.com/sskodje/ScreenRecorderLib/files/6265148/log.txt)
This log is with only multimonitor.

**Comment by sskodje** [comment]
You must set "Log level" to "Trace" in the test app, else it won't record the timings etc.

**Comment by aqibbanday** [comment]
I will do that first thing tomorrow.

**Comment by aqibbanday** [comment]
[log.txt](https://github.com/sskodje/ScreenRecorderLib/files/6269312/log.txt)
Hi,
File attached with trace on. Also it crashed at the end.

Can you share some resources you are using to develop this project, I also want to contribute more to this project.

**Comment by sskodje** [comment]
You need Visual Studio 2019 with "Desktop development with c++" and ".net desktop development" enabled, as well as Windows 10 SDK 10.0.18362. This is enabled in Visual Studio Installer. Then you should be able to fork the project and compile it.

**Comment by aqibbanday** [comment]
> You need Visual Studio 2019 with "Desktop development with c++" and ".net desktop development" enabled, as well as Windows 10 SDK 10.0.19041. This is enabled in Visual Studio Installer. Then you should be able to fork the project and compile it.

Yes, i have all that. I am asking for resources for learning these APIs etc.

**Comment by sskodje** [comment]
Ah right. Unfortunately most of the APIs are poorly documented and there is not a lot of information on it, but you do have some documentation for it [here](https://docs.microsoft.com/en-us/windows/win32/medfound/microsoft-media-foundation-sdk). There is also a book called Developing Microsoft Media Foundation Applications, which you can find online. The most helpful perhaps are the sample projects [here](https://github.com/microsoft/Windows-classic-samples) and [here](https://github.com/microsoft/Windows-classic-samples/tree/master/Samples/Win7Samples/multimedia)

**Comment by aqibbanday** [comment]
Ok. Thanks for this.

**Comment by sskodje** [comment]
From the logs, i can see intermittent very high rendering times, in one instance it used as much as 56 milliseconds on copying a texture, something that should be a fraction of a millisecond operation. What's the specs of the machine you tested on? I have no idea what could cause such spikes, but it could perhaps be thermal throttling in laptops clocking down the GPU.

**Comment by aqibbanday** [comment]
Intel i7 16 GB RAM INTEGRATED GPU.
