### ISSUE TITLE
Error: Invalid index after "Refactoring: formatted code and right-aligned all pointers."

### ISSUE THREAD

**Issue by aqibbanday** [sskodje/ScreenRecorderLib#131]
When I start recording in/after "Refactoring: formatted code and right-aligned all pointers." commit. I am getting this error.
![image](https://user-images.githubusercontent.com/10510359/113972564-6e4cc100-9858-11eb-8079-92370bb90e9f.png)

[log.txt](https://github.com/sskodje/ScreenRecorderLib/files/6276230/log.txt)

**Comment by sskodje** [comment]
I pushed a fix
