### ISSUE TITLE
Make two and more recorders and switch between that

### ISSUE THREAD

**Issue by RomanPlekhanov** [sskodje/ScreenRecorderLib#133]
I need to make several recorders and Start one recorder, then Pause it and Start second recorder. Then Pause second recorder and Start first recorder. Maybe create thirt recorder and Start it when Pause other two recorders. When I do that, I catch an error: _RecordingFailed: Параметр задан неверно._ (translate: Incorrect parameter). Can I create several recorders and start that sequentaly?

Logs:
```
19-04-2021 16:35:02.799 [INFO] [ 22] Screen recorder for req=10316 created: framerate=6, mode=UnconstrainedVBR, bitrate=1000000, quality=1, audioEnabled=True, audioMode=Mono, audioInputDeviceEnabled=True (Volume=0,5), audioOutputDeviceEnabled=True, (Volume=0,5)
19-04-2021 16:35:02.800 [INFO] [ 22] Start: Idle [req=10316]
19-04-2021 16:35:02.842 [INFO] [  8] StatusChanged: Recording [req=10316]
19-04-2021 16:37:01.975 [INFO] [ 61] Pause: Recording [req=10316]
19-04-2021 16:37:01.976 [INFO] [ 61] StatusChanged: Paused [req=10316]
19-04-2021 16:37:02.132 [INFO] [ 61] Screen recorder for req=23 created: framerate=6, mode=UnconstrainedVBR, bitrate=1000000, quality=1, audioEnabled=True, audioMode=Mono, audioInputDeviceEnabled=True (Volume=0,5), audioOutputDeviceEnabled=True, (Volume=0,5)
19-04-2021 16:37:02.132 [INFO] [ 61] Start: Idle [req=23]
19-04-2021 16:37:02.144 [INFO] [ 29] StatusChanged: Recording [req=23]
19-04-2021 16:37:02.148 [INFO] [ 81] StatusChanged: Idle [req=23]
19-04-2021 16:37:02.151 [INFO] [ 81] RecordingFailed: Параметр задан неверно. [req=23]
```

**Comment by sskodje** [comment]
It's a limitation with the Desktop Duplication API that you cannot record the same output more than once. If you do, you get the invalid arguments error. You can record the same output more than once with the Windows Graphics Capture API. May i ask what your use case is for needing this?

**Comment by RomanPlekhanov** [comment]
I have several chats. I chatting parallel and I need to save video for each chat separately.

**Comment by m6t** [comment]
I tested creating multiple recorders and pointing them to different windows to record it works. But for one window I was not able to test that. Maybe you could try to start those charts in different windows and record them simultaneously?
