### ISSUE TITLE
The video is black and green mosaic

### ISSUE THREAD

**Issue by LKMMKL** [sskodje/ScreenRecorderLib#134]
I found  the video is black and green mosaic in a computer（It works well in other computer）.

The OS version is 19042.685 and it is a touch screen computer.

The code what I use is almost the same as the example.

Can you give me some advice on how to solve this problem？

Thank you very much！

**Comment by sskodje** [comment]
Sounds like an issue with the h264 encoder. You can try isolate the issue by disabling hardware encoding and checking if the problem disappears. If so, you can try upgrade your video drivers.

**Comment by LKMMKL** [comment]
It is correct to disable hardware encoding ！
`IsHardwareEncodingEnabled = false `
Thanks your help!
