### ISSUE TITLE
Left, Right, Top, Bottom property doesn't work as expected in multimonitor branch

### ISSUE THREAD

**Issue by aqibbanday** [sskodje/ScreenRecorderLib#137]
Add an option that will allow me to record a region instead of screen or window

**Comment by aqibbanday** [comment]
When i set left, top, right and bottom , it resizes the video instead of recording with the specified points and sizes.

**Comment by aqibbanday** [comment]
@sskodje Any plans to fix this issue.

**Comment by aqibbanday** [comment]
I tried to fix it, but its happening  due to multimonitor screen size.
GetOutputRectsForRecordingSources

**Comment by sskodje** [comment]
I'm working on implementing a new crop/resize functionality that should fix this issue.

**Comment by aqibbanday** [comment]
I would suggest to add an option to select region and that should take the dimensions to record. Like a region recording.

**Comment by sskodje** [comment]
That is what the dimensions in DisplayOptions does.

**Comment by aqibbanday** [comment]
in master branch it it working like that, but in multimonitor branch the video is resized and not the dimensions. You can check by comparing the two branches.

**Comment by sskodje** [comment]
Yes, it's a bug.

**Comment by sskodje** [comment]
Working in 3bce25b1c413ea5126e3773cabadc51a2410d05b , will replace code with something better at a later date.

**Comment by aqibbanday** [comment]
Left and Top is working now, but Right and Bottom is not working.
