### ISSUE TITLE
Resizing window crops the video in WindowsGraphicsCapture mode

### ISSUE THREAD

**Issue by m6t** [sskodje/ScreenRecorderLib#138]
Hi, 
Currently, if you start a recording a window when the window is lets say 500X500 in size, if you resize it to be bigger it crops and sometimes the video becomes green. i was able to mitigate this issue by maximizing the window first then starting the recording then returning the window to normal size. If i do this the window in the recording gets scaled in to the video to fit. 

I wonder if there is a way to set desired resolution so the video file is that size regardless of the starting window size. Or if its possible to downscale the window onto the video if the window is bigger than the recording itself.

But if we could set the starting resolution to 1920x1080 for example this will be enuoght as it behaves correctly if the video is bigger that the window.

Also if there was a callback after first frame drawn it could be wery useful for us.

**Comment by m6t** [comment]
Oh thanks, I will check it out ASAP.

**Comment by sskodje** [comment]
Fixed with 83202d6490ba66d1bba21f0f94e9a7e25449dbe8
