### ISSUE TITLE
dotnet publish stops ScreenRecorderLib working (dotnet 5.0)

### ISSUE THREAD

**Issue by tommed** [sskodje/ScreenRecorderLib#145]
I have the following properties set in my csproj file:

```<OutputType>Exe</OutputType>
        <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
        <PlatformTarget>x64</PlatformTarget>
<RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <PublishSingleFile>true</PublishSingleFile>
        <PublishTrimmed>false</PublishTrimmed>
```

(Ideally, I'd like to get `PublishTrimmed` working too but that's a story for another day.)...

This compiles and the published output doesn't contain anything to do with ScreenRecorderLib (no dll or anything) so I have assumed it's been embedded into the single file(?). When I run this however I get the following cryptic error from .NET as soon as a recording is attempted:

``` Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
 Repeat 2 times:
 --------------------------------
  at <Module>.__security_init_cookie()
 --------------------------------
   at <Module>. <CrtImplementationDetails>.LanguageSupport.InitializeNative(<CrtImplementationDetails>.LanguageSupport*)
   at <Module>.<CrtImplementationDetails>.LanguageSupport._Initialize(<CrtImplementationDetails>.LanguageSupport*)
   at <Module>.<CrtImplementationDetails>.LanguageSupport.Initialize(<CrtImplementationDetails>.LanguageSupport*)
   at <Module>..cctor()
   at ViPro.WindowsKit.Reactions.VideoClipper+<RecordAsync>d__1.MoveNext()
```

I've tried copying over ScreenRecorderLib.dll but this doesn't fix it either. Everything works if I run the Debug program, so it's the resulting publish which is problematic.

Command used to publish: `dotnet publish -c "Release" -p:Platform=x64 ..\services\ViPro.UserService\ViPro.UserService.csproj`

**Comment by tommed** [comment]
I've also tried setting `IncludeNativeLibrariesForSelfExtract` to `true` (default is `false`), but this does not affect the observed behaviour.

**Comment by sskodje** [comment]
Looks like it's a compatibility issue between C++/CLI and .NET 5.0 when using self contained exe files. I found someon with the same issue [here](https://developercommunity.visualstudio.com/t/cannot-embed-ccli-mixed-mode-assembly-in-net-5-sel/1309200). I tested myself, and got the same error on .NET 5.0, but it worked fine with .NET core 3.1.

**Comment by tommed** [comment]
Agreed. I have a temporary workaround by setting `IncludeAllContentForSelfExtract` to \true\ in the .csproj which makes the start-up time take aaaaaaages (because the .exe is essentially a .cab which gets extracted to a temporary location) but used in combination with `IncludeNativeLibrariesForSelfExtract` allows the .NET program to avoid a new "self-contained embedded runtime" (not sure how else to describe this?) and just run everything in a standard folder (once extracted). It isn't a great workaround because of the extended start-up time, but it does now work!

**Comment by sskodje** [comment]
Good to hear you got it working! It seems like `IncludeAllContentForSelfExtract` emulates the .net core 3.1 behavior. It seems managed C++ is not well supported for single-file deployment, according to this warning on https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#including-native-libraries 

> Managed C++ components aren't well suited for single-file deployment and we recommend that you write applications in C# or another non-managed C++ language to be single-file compatible.
