### ISSUE TITLE
Audio indicator

### ISSUE THREAD

**Issue by maximzhemerenko** [sskodje/ScreenRecorderLib#149]
Hello community, thank you for for this library. Does it support audio indication like "equalizer"? I need to implement something like that 
<img width="316" alt="image" src="https://user-images.githubusercontent.com/7162289/123881492-81e66000-d94d-11eb-80ef-450da870714b.png">
Could someone explain, can I receive realtime information to build this graphic?

**Comment by sskodje** [comment]
That's not in the scope of this library, no. But the audio information can be read using a library like NAudio, so you can probably find some tutorials or open source code for that.
