### ISSUE TITLE
Turn off screen capture (force black video)

### ISSUE THREAD

**Issue by maximzhemerenko** [sskodje/ScreenRecorderLib#150]
Has this library ability to temporary turn off the screen capture (capture black video)?

**Comment by sskodje** [comment]
No, but I'll add it as a feature request :)

**Comment by maximzhemerenko** [comment]
Thank you, @sskodje !

**Comment by maximzhemerenko** [comment]
Hi @sskodje, could you please tell me, when I can expect this feature to be ready to use? Or maybe you need some help from my side with this task?

**Comment by sskodje** [comment]
Hello! I've basically had a feature freeze on the main branch until i can get a new, completely rewritten version released. I'ts tough to say when that is done, but i''d say at least several more weeks. If you need it like right away, you can just make the changes on your own fork. It's only a few lines you need to change. A method to toggle the functionality on and off in Recorder.h, a bool to store the value in internal_recorder.h, and check for the bool [here](https://github.com/sskodje/ScreenRecorderLib/blob/ca95651ce2f957dd8f8a0848302890e12271c541/ScreenRecorderLibNative/internal_recorder.cpp#L963) and [hre](https://github.com/sskodje/ScreenRecorderLib/blob/ca95651ce2f957dd8f8a0848302890e12271c541/ScreenRecorderLibNative/internal_recorder.cpp#L659)

**Comment by maximzhemerenko** [comment]
Ok, thank you, I will try to do this, I will ask you if something I will not understand :)

**Comment by sskodje** [comment]
Video capture on individual sources can be toggled off or on using the new dynamic options feature implemented with 83202d6490ba66d1bba21f0f94e9a7e25449dbe8
