### ISSUE TITLE
Portrait mode - wrong resolution?

### ISSUE THREAD

**Issue by czuczorf** [sskodje/ScreenRecorderLib#153]
Hi!

Great lib, easy to use! ;-)

I've tried to record in portrait mode(display orientation) and was hoping for a 1080x1920 video file resolution,  but the recording is 1920x1080 and the captured screen is downsized-fitted into the middle.

Is it possible to make the recording in 1080x1920 resolution?

Thanks!
Bests
Feri

**Comment by sskodje** [comment]
If it doesn't work, it's a bug. I'll look into it :)

**Comment by czuczorf** [comment]
Thanks! :-)


Sverre Skodje ***@***.***> ezt írta (időpont: 2021. júl. 21.,
Sze, 23:23):

**Comment by sskodje** [comment]
This should be fixed with 83202d6490ba66d1bba21f0f94e9a7e25449dbe8
