### ISSUE TITLE
Is there a way to check the Main monitor among multiple monitors?

### ISSUE THREAD

**Issue by SID9-HoneyBee** [sskodje/ScreenRecorderLib#154]
I am using 4 monitors connected.
If you enter the display settings of the window, you can check (identify) the number of each monitor and you can check the main monitor.

Can I select the number of each monitor and the main monitor in advance before recording?

Also, is it possible to get the display where a specific application is running?

**Comment by sskodje** [comment]
I'm not sure what those numbers are based on, but i don't think you can get them via the windows APIs. Identifying the main monitor is easy, as it will always have left and top coordinates 0, so for example [0,0,1920,1080] will be the main monitor.

To get the display a specific application resides is not completely trivial again, as an application can span several displays. But you can check the window coordinates against the display coordinates and see which ones it fits inside.
