### ISSUE TITLE
Contents being written to stream late.

### ISSUE THREAD

**Issue by TheBlackPlague** [sskodje/ScreenRecorderLib#155]
Due to a lack of documentation available on the repository, I can't tell if what I'm doing is completely wrong (and that's why content is not being written) or whether this is a genuine bug. 

```cs
private static readonly MemoryStream OutputStream = new MemoryStream();
private static Recorder Recorder; // A recorder using Windows Graphic Capture API (in Video mode — 60 FPS, 1MB Bitrate)

public static void Start()
{
    Recorder.Record(OutputStream);
}
```
and then checking the stream's length and capacity every 100ms using:
```cs
Console.WriteLine(OutputStream.Capacity);
Console.WriteLine(OutputStream.Length);
```

It seems that both the `Capacity` and `Length` remain 0 at all times. Any assistance or information that can be provided is helpful!

**Comment by TheBlackPlague** [comment]
Update: It seems that this issue is less with the contents not being written to stream but more with the fact that contents are written to stream later than when they should be. The stream gets contents written to it anytime between 3s-5s after `Recorder.Record()` has been callen. 

Is this normal behavior that the recording starts so late? 

Also, given that the stream contents are written at a random time between 3s and 5s, is there any example or documentation on how to read the latest frame from this stream?

**Comment by sskodje** [comment]
5 seconds is oddly excessive, but unfortunately there are techical reasons why there is a delay. The MF video encoder batches frames before encoding, and as far as i know it will batch 0.7 seconds of frames before writing the first one. For me, it will have around 1 second delay. For your needs, i think you need to go a bit more low level and skip the video encoder directly and grab the frames and encode them yourself, or perhaps you can use a tool like FFMPEG.

**Comment by TheBlackPlague** [comment]
> 5 seconds is oddly excessive, but unfortunately there are techical reasons why there is a delay. The MF video encoder batches frames before encoding, and as far as i know it will batch 0.7 seconds of frames before writing the first one. For me, it will have around 1 second delay. For your needs, i think you need to go a bit more low level and skip the video encoder directly and grab the frames and encode them yourself, or perhaps you can use a tool like FFMPEG.

Any help in how to do that? Furthermore, how would you advise I get the frames directly with the API provided? Any assistance would be substantial.

**Comment by sskodje** [comment]
Check out this sample which does what you intent to do, record the screen and view it in real time. I'm assuming you want to create some form of screen sharing tool or similar.

https://github.com/microsoft/Windows-classic-samples/tree/main/Samples/DXGIDesktopDuplication

ID3D11Texture2D are raw image samples that reside in the graphics card memory. This sample only renderes them to a swapchain locally, but the idea is the same. 

To view them remotely, you need to encode the frames, transfer them, number them, and send them to the client, and render them to the clients swapchain again. To encode them, you can use Media Foundation. [This example](https://github.com/ashumeow/webrtc4all/blob/master/gotham/MFT_WebRTC4All/test/test_encoder.cc) uses Media Foundation to encode the individual frames to H264. The frame is encoded to a IMFSample, from which you can get a IMFMediaBuffer, from which you can get the raw encoded byte array.

To reverse the process, you create a IMFMediaBuffer, put the byte array back in, create a IMFSample and add the buffer to it. You can see this process [here](https://github.com/sskodje/ScreenRecorderLib/blob/ca95651ce2f957dd8f8a0848302890e12271c541/ScreenRecorderLibNative/internal_recorder.cpp#L1956). You now have a IMFSample which you can query for a ID3D11Texture2D [like so](https://stackoverflow.com/a/43448769/2129964). Ready to render!


I can't give you any more assistance unfortunately. I advice looking up a tutorial on working with DirectX and Media Foundation.

**Comment by TheBlackPlague** [comment]
I decided to use the `Windows.Graphic.Capture` API directly with SharpDX (with a bit of interop) and avoid using ScreenRecorderLib. Nothing against it, just the native implementation fits my use-case better. I had to get the frames and pass them into a neural network.

Thank you for all the help you provided. 

I'll edit this reply with the project link (once I open-source it) on how I solved the problem in case anyone else in the future runs into the same issue. I'll also change the name. You may choose to implement this later on, in which case I'll also edit the reply accordingly.
