### ISSUE TITLE
Content files from all packages are copied into project

### ISSUE THREAD

**Issue by jairbubbles** [sskodje/ScreenRecorderLib#158]
Hello,

When referencing `ScreenRecorderLib` and other packages in the same `.csproj`, for instance:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <Platforms>x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ScreenRecorderLib" Version="3.1.1"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
  </ItemGroup>
</Project>
```

All content files from packages ended up being copied in the project:  
![image](https://user-images.githubusercontent.com/15875066/129760788-caebf5f6-3760-45a7-b3ac-1acd1a9817d3.png)

All this is linked to the target `CopyLinkedContentFiles` in `ScreenRecorderLib.targets`:
```xml
  <Target Name="CopyLinkedContentFiles" BeforeTargets="Build">
    <Copy SourceFiles="%(Content.Identity)"
			  DestinationFiles="%(Content.Link)"
			  SkipUnchangedFiles='true'
			  OverwriteReadOnlyFiles='true'
			  Condition="'%(Content.Link)' != ''" />
  </Target>
```

Packaging native binaries with NuGet is clearly not an easy task but I've seen some package that use  `Content` nodes:
```xml
<ItemGroup>
    <Content ... />
    <Content ... />
    <Content ... />
</ItemGroup>
```
You could also use the `runtimes` folder (see https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#architecture-specific-folders) but it probably works only when consuming with a recent MsBuild.

**Comment by sskodje** [comment]
I'm unfortunately not super-knowledgeable about Nuget, but i think i see what the problem is. Thanks 👍

**Comment by jairbubbles** [comment]
I could give it a try if you'd like.

**Comment by sskodje** [comment]
Sure, i'm glad for all help!

**Comment by jairbubbles** [comment]
Hi @sskodje, I started a very imple PR => #159.

For now, it's only compatible with the (not that) new way of referencing NuGet packages. I can do something for `pacakges.config` too if you feel like it's needed.

**Comment by jairbubbles** [comment]
Hi @sskodje, I started a very imple PR => #159.

For now, it's only compatible with the (not that) new way of referencing NuGet packages. I can do something for `packages.config` too if you feel like it's needed.

**Comment by sskodje** [comment]
It would be nice to have support for packages.config as well, if you can add it. I know it's dated, but it's still used as default for many project types to my knowledge.

**Comment by jairbubbles** [comment]
It's more complicated than expected so I'm proposing a simple fix:  
https://github.com/sskodje/ScreenRecorderLib/pull/160

**Comment by sskodje** [comment]
Thanks for the thorough reproduction steps, i'm now able to reproduce.
