### ISSUE TITLE
How to get current video frame number?

### ISSUE THREAD

**Issue by Mapiarz** [sskodje/ScreenRecorderLib#162]
How can I get the current frame number while recording?

I could calculate the frame number given start time, current time and framerate BUT even if I set fixed framerate in video options and framerate to 30, when I inspect the video in VLC the framerate is about ~21.

Any ideas?

**Comment by Mapiarz** [comment]
> There's no current functionality for what you want. I can add it to the TODO list for next version, or if you need the functionality right away you can pretty easily follow and copy one of the [existing callback paths ](https://github.com/sskodje/ScreenRecorderLib/blob/ca95651ce2f957dd8f8a0848302890e12271c541/ScreenRecorderLib/Recorder.h#L15) and create one for your needs.

Thanks! 

When is next release scheduled?

**Comment by sskodje** [comment]
If i don't run into more issues, sometime in the next few weeks.

**Comment by Mapiarz** [comment]
@sskodje Hi! I added a PR. I hope it's okay and will be merged soon as it is timely for me. LMK if there are any issues I should resolve.

How are we looking for next official release? If it made it into the next release, which hopefully will be published soon, it'd make my life a whole lot easier.

Thanks

**Comment by sskodje** [comment]
Thanks for the PR! I have already merged it into the branch for the next release. As for the schedule, all base functionality is now tested and working, so getting close to release.

**Comment by sskodje** [comment]
This is now merged in with 83202d6490ba66d1bba21f0f94e9a7e25449dbe8
