### ISSUE TITLE
How to make a Windows service process?

### ISSUE THREAD

**Issue by vishnumuthu** [sskodje/ScreenRecorderLib#164]
(I am new to c#) I am trying to make the process as windows service.
I am getting the error "A resource is not available at the time of the call, but may become available later."
Have attached the code as text file below,
Let me know if this is the right way to do it!

[ScreenRecord.txt](https://github.com/sskodje/ScreenRecorderLib/files/7111940/ScreenRecord.txt)
[Service.txt](https://github.com/sskodje/ScreenRecorderLib/files/7111941/Service.txt)

**Comment by lzwierko** [comment]
Hi I've tired, and same. After some digging I think that Windows restricts access to display from Windows service, even if it's running as user currently logged in our even if the service spawns a new process.

**Comment by sskodje** [comment]
This is not possible for windows security reasons.
