### ISSUE TITLE
Memory leak when recording video on process dwm.exe

### ISSUE THREAD

**Issue by mmoutonn** [sskodje/ScreenRecorderLib#165]
Hi,
I notice that the memory of the process dwm.exe (on windows 10) is growig everytime a run a video record.
dxm.exe take about 8Mo for each video (memory increasing doesn't depends on video duration).

![image](https://user-images.githubusercontent.com/90709852/133287910-7d5a1afd-4162-4833-bf99-43fbb5672bf3.png)

Environnement:
windows 10
screenrecorderlib 3.1.2.0

Here you can find a code sample to reproduce this issue.

    public class Recorder_
    {
        object _rec = null; // Recorder _rec;
        // Stream _outStream;
        string videoPath = Path.Combine(Path.GetTempPath(), "test.mp4");
        bool isVideoComplete = false;

        public void CreateRecording()
        {
            if (File.Exists(videoPath))
            {
                File.Delete(videoPath);
            }

            _rec = Recorder.CreateRecorder(generateRecorderOptions());
            ((ScreenRecorderLib.Recorder)_rec).OnRecordingFailed += Rec_OnRecordingFailed;
            ((ScreenRecorderLib.Recorder)_rec).Record(videoPath);
        }
        public void EndRecording()
        {
            Console.WriteLine("Try stop video");
  
            // ajout l'évènement de fin de record
            ManualResetEvent resetEvent = new ManualResetEvent(false);
            ((ScreenRecorderLib.Recorder)_rec).OnRecordingComplete += (s, args) =>
            {
                Console.WriteLine("OnRecordingComplete");
                isVideoComplete = true;
                resetEvent.Set();
            };
            ((ScreenRecorderLib.Recorder)_rec).Stop();
            resetEvent.WaitOne(5000);

            Console.WriteLine("video status {1} in {0}", videoPath, isVideoComplete);
        }
        private void Rec_OnRecordingFailed(object sender, RecordingFailedEventArgs e)
        {
            string error = e.Error;
        }
        private void Rec_OnStatusChanged(object sender, RecordingStatusEventArgs e)
        {
            RecorderStatus status = e.Status;
        }
    }

    class Program
    {

        static void Main(string[] args)
        {
            Recorder_ r = new Recorder_();
            r.CreateRecording();
            Thread.Sleep(5000);
            r.EndRecording();
            Thread.Sleep(1000);
        }
    }
    
Do you know this issue ?
I tried different recorder option without success.
Any suggestion ?

**Comment by sskodje** [comment]
I'm unable to reproduce the issue on my end. Do you use Intel graphics to encode? I found several recent issues with Intel drivers causing memory leaks when googling it.

**Comment by mmoutonn** [comment]
Hi, thanks for your quick answer.
I reproduce the issue on a AWS ec2 instance (t2 medium, no GPU).
I don't on my laptop. 
Finaly a simple 'windows update' fix it. The issue was on microsoft part.

Sorry for false warning.
