### ISSUE TITLE
Monitor selection fails when multiple adapters present

### ISSUE THREAD

**Issue by hakito** [sskodje/ScreenRecorderLib#17]
My computer has two display adapters (with 3 displays). With the TestApp I can only record on with the first item provided in _ScreenComboBox_.

On line https://github.com/sskodje/ScreenRecorderLib/blob/0254ac07d5e8a15f7bbb5fbdf2634ef13e80c169/ScreenRecorderLib/internal_recorder.cpp#L641
the recording is always limited to the primary display adaptger (by providing a nullptr) here.

Instead of using a Monitor number in the RecorderOptions (which is only valid in the adapter's context), I'd suggest to use [Screen.DeviceName](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.screen.devicename?view=netframework-4.7.2#System_Windows_Forms_Screen_DeviceName) which is a string like `\\.\DISPLAY4`. This corresponds to [DXGI_OUTPUT_DESC.DeviceName](https://docs.microsoft.com/en-us/windows/desktop/api/dxgi/nf-dxgi-idxgioutput-getdesc).

**Comment by sskodje** [comment]
Thanks for the info! I didn't think about multiple adapters. I'll have a look at it over the weekend.

**Comment by hakito** [comment]
Did you have time to think about it?

**Comment by sskodje** [comment]
Yeah, I think i have a solution ready, just have to test it some more to make sure it works on different adapters etc :)

**Comment by sskodje** [comment]
Fixed in c2410d7 by changing configuration to use "DeviceName" as suggested. I'd love feedback if all is working properly, as i don't have a great variety of monitors and graphics cards to test with.

**Comment by hakito** [comment]
Great! I think I can test this until friday. I'll close the issue if it works.

**Comment by hakito** [comment]
Sorry - Forgot to close this issue
