### ISSUE TITLE
 Do we have an option to record an application by windows process id?

### ISSUE THREAD

**Issue by aadithancsg** [sskodje/ScreenRecorderLib#171]
Hi

Do we have an option to record an application by windows process id?

**Comment by sskodje** [comment]
RecorderOptions options = new RecorderOptions
            {
                DisplayOptions = new DisplayOptions
                {
                    WindowHandle = YourWindowHandleFromYourMainForm
                },
	            RecorderApi =WindowsGraphicsCapture
            };

           Recorder rec = Recorder.CreateRecorder(options);

There is examples on the readme, and sample projects.

**Comment by aadithancsg** [comment]
Thanks. It works for me however i am seeing a lot of flickering in the recording. I am seeing the same problem with Test Winform App as well.  Can we avoid that by modifying any setting in video options?

**Comment by sskodje** [comment]
I'm not sure what could cause flickering, i haven't seen that issue before. If the flickering is only manefested in the video and not in windows, the only thing i can think of i try enable or disable hardware encoding, or turn on or off fixed framrate.

**Comment by aadithancsg** [comment]
Tried it but no luck. It happens only when we use window handle in Display options and it is replicable in your sample winform app too.
