### ISSUE TITLE
Recorder status marked Idle when file is still locked

### ISSUE THREAD

**Issue by MJWherry** [sskodje/ScreenRecorderLib#173]
I have a process that moves a file after recording. I poll until the recorder status is idle then i try to move the file

After doing this a bunch, ive found that even though the recorder status is set to idle, the file is still locked causing the file movement to throw an ex.

**Comment by MJWherry** [comment]
Still getting errors on starting recording after a bunch of starting/stopping (est ~2k) even after using flags and waiting in the start/finished recording events.

attached is the recorder log. Even if i have a flag in the OnRecordingFailed event and try to recreate the recorder after that event is thrown (disposing, recreation on the next test setup) it still fails.

also, the message after running the tests in the nunit runner in jetbrains IDE is attached, unsure if useful as it's only the last 100 lines
[recorder.log](https://github.com/sskodje/ScreenRecorderLib/files/7463070/recorder.log)
[jetbrains nunit runner.txt](https://github.com/sskodje/ScreenRecorderLib/files/7463071/jetbrains.nunit.runner.txt)

**Comment by sskodje** [comment]
From the logs, what appears to be happening is a failure in the graphics driver resulting in DXGI_ERROR_DEVICE_REMOVED error as access to the graphics driver is temporarily lost. It could be due to overheating for example, or a driver issue.
I've made improvements to the error handling in the next release i'm working on, and i've attached the latest files if you wish to test if it solves the problem. It's unfortunately not backwards compatible due to changes to the RecorderOptions class, but it hopefully should not be too much work to test.

[Release.zip](https://github.com/sskodje/ScreenRecorderLib/files/7464632/Release.zip)

**Comment by MJWherry** [comment]
will run today with release and post results later

**Comment by MJWherry** [comment]
Even less tests were able to run with that release, failing after the starting recording again, attached was the recorder log and test console output
[recorder.log](https://github.com/sskodje/ScreenRecorderLib/files/7470316/recorder.log)
[jetbrains nunit runner2.txt](https://github.com/sskodje/ScreenRecorderLib/files/7470323/jetbrains.nunit.runner2.txt)

**Comment by MJWherry** [comment]
looking at that output from the console runner, the following log line logs the recorders status message, going to try to wrap that in a try/catch also

**Comment by MJWherry** [comment]
I think the issue may be that the software im writing tests for also uses the audio input devices, which is why the console log gets spammed with 'Unable to open device' and the fact that i see issues in the app log regarding the same issue. Will try removing recording of audio all together

**Comment by MJWherry** [comment]
also per the return code in the test runner
https://stackoverflow.com/questions/55722844/error-in-dynamic-programming-problem-what-does-runtime-error-exit-code-is-10

**Comment by sskodje** [comment]
Do you have any sort of power saving that kicks in after a certain time to turn off the monitor? I may have found some issues with that.

**Comment by MJWherry** [comment]
no, the tests are ui automation tests, so there is no chance at screen locking or screen saver

**Comment by MJWherry** [comment]
disabling the audio did nothing, still get the 'Unable to open device message.

start and stop ~2k times (waiting until events are thrown to either move or delete recording file)
after a random number of tests run, the recorder (on start recording) creates the file but immediately moves to idle and event was thrown (flag for recorder errored)
during teardown, since recorder is errored, deletes left over file since recording failed
following tests setup sees recorder was errored and tries to recreate, and start recording
though even in recreation the same stuff happens (recorder fails and goes to idle and event hits, file made but no data)
after a while continuing this crashes the test process giving that jetbrains console log and error of unable to open device

any other information i can provide lmk

**Comment by sskodje** [comment]
I've been doing some testing, and have been unable to reproduce the issue with 5000 recordings in a row over the span of an hour, so i'm basically aiming blind here, but there's some diagnostic steps we could take.

First would probably be, if you are using hardware encoding, can you switch to software encoding (or vice versa) and see if it fixes it? Media Foundation uses encoders supplied by the different vendors like Intel for hardware encoding, so this would rule out a buggy driver.

If that is unsuccessful, my next step would be to test outside of the testing framework, just on the very slim chance it causes a memory leak or something. Just do a console app and run a few thousand recordings to test, with for example.

A third step is testing on a different physical machine, in case there is a hardware issue.
