### ISSUE TITLE
Empty .mp4 file when trying to record screen

### ISSUE THREAD

**Issue by igorrecioh** [sskodje/ScreenRecorderLib#177]
Hi all,

I have been searching any issue related to my problem but I have not found (maybe it's there but I haven't seen it... sorry in that case).

I am trying to use screen recording with ScreenRecorderLib but no success. The .mp4 file is successfully created but is totally empty, 0 bytes. On the other hand, if I use slideshow option or screenshot, it works fine. 

Not sure if I am doing something wrong. These are my options:

```csharp
RecorderOptions options = new RecorderOptions
            {
                RecorderMode = RecorderMode.Video,
                RecorderApi = RecorderApi.WindowsGraphicsCapture,
                //If throttling is disabled, out of memory exceptions may eventually crash the program,
                //depending on encoder settings and system specifications.
                IsThrottlingDisabled = false,
                //Hardware encoding is enabled by default.
                IsHardwareEncodingEnabled = false,
                //Low latency mode provides faster encoding, but can reduce quality.
                IsLowLatencyEnabled = false,
                //Fast start writes the mp4 header at the beginning of the file, to facilitate streaming.
                IsMp4FastStartEnabled = false,
                DisplayOptions = new DisplayOptions
                {
                    WindowHandle = windows[windowIndex].Handle
                }
            };
```

My host:
Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz   3.41 GHz
16Gb RAM
Edition:	Windows 10 Business
Version:	21H2
Installed	‎14/‎09/‎2021
Build	19044.1466
Experience	Windows Feature Experience Pack 120.2212.3920.0

Thanks a lot in advance

**Comment by sskodje** [comment]
Nothing looks out of order, but there are a lot of bugs and issues with windows/media foundation that can affect video encoding. I suggest checking your log and see if you can coax an error out of it. I also uploaded a new version today with many large changes to the recording process, you can check if it works better for you.

**Comment by igorrecioh** [comment]
Thanks a lot @sskodje ! I am trying now new version. Will keep you updated :)

**Comment by sskodje** [comment]
I'm very sorry for replying so late, i had missed your reply. Did you get this sorted out? If the library is not recognized, it probably means you compile as "Any CPU" instead of choosing a platform like x64 or x86. Any CPU is unfortunately not supported.

**Comment by igorrecioh** [comment]
Hi @sskodje! Don't worry for the late response, I am grateful for your nice work on this project! I will check what you say and keep updated! Thanks a lot!

**Comment by igorrecioh** [comment]
I am back! I have updated to 5.1.0 NuGet. Now Recorder object is recognized, so no compilation errors.

The problem now comes when trying to run the project. I am compiling it as Debug-x64 
![image](https://user-images.githubusercontent.com/14996883/153842779-ad381058-4a79-49e6-851b-edb871c9faed.png)

But for some reason, when I run it I get this error:
![image](https://user-images.githubusercontent.com/14996883/153843024-9fcfbfd7-2453-4652-af83-42910591be17.png)

I think that it is recognizing the compilation as Any but it is not the case. I am missing something when building?
Thanks!

**Comment by igorrecioh** [comment]
Well, I have bypassed the error by "tunning" ScreenRecorderLib.targets  file like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <Target Name="PlatformCheck" BeforeTargets="InjectReference">
   
  </Target>

  <Target Name="InjectReference" BeforeTargets="ResolveAssemblyReferences">
  <ItemGroup>
    <Reference Include="ScreenRecorderLib" Condition="'$(Platform)' == 'x86'">
      <HintPath>$(MSBuildThisFileDirectory)x86\ScreenRecorderLib.dll</HintPath>
    </Reference>
	<Reference Include="ScreenRecorderLib" Condition="'$(Platform)' == 'Win32'">
      <HintPath>$(MSBuildThisFileDirectory)x86\ScreenRecorderLib.dll</HintPath>
    </Reference>
    <Reference Include="ScreenRecorderLib">
      <HintPath>$(MSBuildThisFileDirectory)x64\ScreenRecorderLib.dll</HintPath>
    </Reference>
  </ItemGroup>
  </Target>
</Project>
````
It is not the best option, but this is provisional. Good, now I can run my project and video is generated (seems correctly) because size is not 0. Unfortunately, when trying to play the generated video, it says corrupted or something similar. This is happening when playing in Windows10 or Ubuntu 20.04.3. Maybe it is related to codecs?

**Comment by igorrecioh** [comment]
Okey, I see the problem here. I was not moving the mouse when running my project nor clicking nothing. If I move it or click in some icons, it generates fine the video and is playable later! Let's close this!
