### ISSUE TITLE
Integrating in Selenium: Screen Recording when running headless

### ISSUE THREAD

**Issue by juneremonte** [sskodje/ScreenRecorderLib#180]
It's not issue but rather a question: I am trying to implement this very useful tool in my selenium project is there a way to still record my test eve if I am running in headless mode? Thanks

**Comment by sskodje** [comment]
No, unfortunately it needs to run in a window to be able to record it. To my knowledge, the best you can do it to get the headless browser to send you screenshots of the rendered page.
