### ISSUE TITLE
Lock screen issue with v5.x.x

### ISSUE THREAD

**Issue by xujie6** [sskodje/ScreenRecorderLib#183]
Hi

I updated the version to v5.1.0 via Nuget yesterday and found that once I lock screen when it's recording, the recorder will  be interrupted and crash.  The oldder version v3.x.x has no this issue.

This is the log file:
[ScreenRecorderLib.log](https://github.com/sskodje/ScreenRecorderLib/files/8183644/ScreenRecorderLib.log)
.

**Comment by sskodje** [comment]
Thanks for the report, i found the issue. I'll make an update later today probably with some other fixes.
