### ISSUE TITLE
Support <Platforms> tag in csproj

### ISSUE THREAD

**Issue by LaurentM-Ubi** [sskodje/ScreenRecorderLib#184]
When you use `<Platforms>` instead of `<Platform>`, you can't use the libary because of this check

<img width="732" alt="image" src="https://user-images.githubusercontent.com/81652553/157486656-fbf54ddf-10f2-4f58-9a42-dc7450f787ca.png">

**Comment by sskodje** [comment]
thanks for letting me know, i'll fix it 👍

**Comment by sskodje** [comment]
I was looking to recreate this issue, but couldn't manage on a clean .net 6 project. Do you have a sample <PropertyGroup> block where this occurs?

**Comment by LaurentM-Ubi** [comment]
Hello, I just tried to create a new project to reproduce the issue, and with this empty project it works with <Platforms>.
So I don't know any more what was the issue.
I know that there are some bugs in VS with this <Platforms> tag, and sometimes Visual Studio is lost with the configuration manager. So maybe it was something like that.
Anyway I don't have a repro for you, so I'm closing the issue. Will reopen it if I find something. 
Thanks and sorry for the inconvenience.
