### ISSUE TITLE
How to upgrade from version 3.1.2 to 5.1.1

### ISSUE THREAD

**Issue by SID9-HoneyBee** [sskodje/ScreenRecorderLib#185]
After the package update, it was confirmed that many parts of the source code had to be modified.

To refer to this, I tried to run the project's DemoApp, but it is impossible to check due to numerous errors.

There is a difficulty in compiling the attached DemoApp.

How can I easily fix a lot of things that have changed?

**Comment by sskodje** [comment]
Yes, there's quite a few breaking changes, mostly related to the configuration layout. [You can check out the wiki](https://github.com/sskodje/ScreenRecorderLib/wiki/Quickstart-guide-v5.x.x) for some examples. Are you using vs 2019 or 2022?
