### ISSUE TITLE
Question: Can we convert video from .wmv to .mp4 using this library? 

### ISSUE THREAD

**Issue by ankit4vision** [sskodje/ScreenRecorderLib#189]
**Question: Can we convert video from .wmv to .mp4 using this library?**

I have a requirement and based on that I have a list of pre-recorded videos in .wmv formate. I need to convert all of them in .mp4.

Currently, I am able to record the video in **.mp4** using this lib, But is there any way to convert the video in .mp4 from the existing video?

**Comment by sskodje** [comment]
No, this library is focused on screen recording, not video conversion :) I suggest looking into ffmpeg or the many tools built around it for video conversion.
