### ISSUE TITLE
Im still getting an issue where i get an error with no feedback on what the issue is...implementing your sr into an automation for unit testing to save a video of a failing test (they are UI unit tests), recording to a memory stream and running a test fails yet pointing to a file path does not...it errors out on _rec.Record(_outStream) where outstream=memorystream

### ISSUE THREAD

**Issue by sskodje** [sskodje/ScreenRecorderLib#19]
_Originally posted by @MJWherry in https://github.com/sskodje/ScreenRecorderLib/issues/18#issuecomment-436397750_

**Comment by sskodje** [comment]
I split this out as a new issue. As mentioned, i'd love to see your recorder initialization code to figure this out.

**Comment by MJWherry** [comment]
Sure, attached is my wrapper for the lib. Running them from a test runner via win forms and the outstream method works fine, though running them via Jetbrains rider build in unit test runner yields no avi and throw error in recorder but no data
[RecorderWrapper.txt](https://github.com/sskodje/ScreenRecorderLib/files/2557651/RecorderWrapper.txt)

**Comment by sskodje** [comment]
This issue should be fixed with 56890487b5aec7a8530ac8e8154efc6e28efb881. I've updated NuGet as well. Let me know if there are any more problems.

**Comment by MJWherry** [comment]
Tested and works like a charm thank you kindly!
