### ISSUE TITLE
can not work on windows server 2012 standard 

### ISSUE THREAD

**Issue by DNetORM** [sskodje/ScreenRecorderLib#190]
system.IO.FileNotFoundException: Failed to load file or assembly “ScreenRecorderLib.dll”or one of its dependencies. The specified module cannot be found。
filename:“ScreenRecorderLib.dll”
   在 pdfdemo.Form1.CreateRecording()
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

vc_redist.x64 installed，Media Foundation installed
still can not work on windows server 2012 standard 
what reason?

**Comment by sskodje** [comment]
I figured out there's a dependency that requires Windows 10/server 2016, which is causing it to fail on server 2012. I'll see if it's possible to work around it.

**Comment by DNetORM** [comment]
Good, so has this problem been fixed

**Comment by sskodje** [comment]
I think i've found a fix, but i'll have to do some testing over easter to make sure i don't break antything on other windows versions.

**Comment by sskodje** [comment]
This should be fixed with v1.5.2
