### ISSUE TITLE
 using Bluetooth headset, the recording is abnormal

### ISSUE THREAD

**Issue by Leo-23333** [sskodje/ScreenRecorderLib#191]
On Windows 11, when using Bluetooth headset, the Audio input recording is abnormal

![image](https://user-images.githubusercontent.com/96120229/161887163-c4e86d3d-abd9-4d58-bf85-06f9c4d995b5.png)

**Comment by sskodje** [comment]
If you don't mind, could you make a recording with "log to file" and "log level" set to trace and post the log file here?
