### ISSUE TITLE
Saved screen clipped after I run UAC prompt

### ISSUE THREAD

**Issue by hanhsia** [sskodje/ScreenRecorderLib#192]
It look the rect setting is incorrect if the screen duplication is reset. 
Repro:
1. run TestConsoleAppDotNetCore
2. open a cmd window and run it as admin
3. check the video. 
Before. 
![image](https://user-images.githubusercontent.com/13341722/164589209-d414889b-3c37-44e4-8395-447082346230.png)
After:
![image](https://user-images.githubusercontent.com/13341722/164589275-0b48096a-a689-45ff-8b52-18a08b714e0f.png)

**Comment by sskodje** [comment]
Thanks for the reproduction steps. I'll look into it :)

**Comment by sskodje** [comment]
Should be fixed with a785880c0c06dd3c8d17d0c526cbf3760b4f859d
