### ISSUE TITLE
Have any plan support sending H264 stream to server by rtmp/rtsp?

### ISSUE THREAD

**Issue by Riton2013** [sskodje/ScreenRecorderLib#195]
I am trying to send H264 stream to server but failed, it can't be player after sending. Maybe I did wrong with video format? I get 3 kinds of buffer, one of them is fixed 8-byte length, and others I guess they are video and audio. It take me a lot of time.

**Comment by sskodje** [comment]
I don't have any plans for that in the immediate future, but I made a small demo project on how to remux to FLV and send to a RTMP server with FFMPEG you can check out here: https://github.com/sskodje/ScreenRecorderLib/tree/streaming_demo/TestConsoleAppStreaming

**Comment by Riton2013** [comment]
Doing test all day yesterday, FFMPEG is not good enough, delay 2 seconds at begin, 2 hour later(keep pushing data), delay 7 seconds. I try to compare with OBS, obs is good. Anyway, very very very thanks for your help!!
