### ISSUE TITLE
Can not choose audio input device

### ISSUE THREAD

**Issue by sskodje** [sskodje/ScreenRecorderLib#2]
Need a way to choose audio device for capture.

**Comment by FoxPride** [comment]
Greetings, sskodje!
Thx very much for mouse clicks feature as I requested. 
Please take a look at my pull request for this issue.

**Comment by sskodje** [comment]
I'll have a look tomorrow! Thanks for contributing!

**Comment by sskodje** [comment]
Implemented with d5d95cf94212a5ebc30465c82e09fe786d17a06e
