### ISSUE TITLE
Capture mouse clicks feature

### ISSUE THREAD

**Issue by FoxPride** [sskodje/ScreenRecorderLib#20]
Hi! Could you implement this feature, please? Something like in Captura project (https://github.com/MathewSachin/Captura/blob/master/src/Captura.MouseKeyHook/MouseKeyHook.cs). It shows mouse clicks on recorded video.

**Comment by sskodje** [comment]
I'm sorry, but I don't have time to implement new features atm. I'm happy to accept pull requests though if you want to implement it yourself.

**Comment by sskodje** [comment]
This feature was implemented in 6bc4513a27575b7da74fbaf7440fb8abcd38771b
