### ISSUE TITLE
Recording windows by handle does not show cursor

### ISSUE THREAD

**Issue by FoxPride** [sskodje/ScreenRecorderLib#203]
Perhaps this is the right behavior, but mouse clicks are displayed. Is it possible to add a cursor record in this case?

Thanks in advance!

**Comment by sskodje** [comment]
It's a bug. I'm working on a fix :)

**Comment by sskodje** [comment]
Should be fixed with 49260fa2efa23e2d0e84aacd7c80c320354bc6ee
