### ISSUE TITLE
Access violation reading location

### ISSUE THREAD

**Issue by peder2key** [sskodje/ScreenRecorderLib#205]
Hello :)

Thanks for a great library. I have been using it with the basic usage example but after i while it fails with: 

![Snag_13a73f54](https://user-images.githubusercontent.com/3829467/175937295-db9d45ba-e802-4b36-b82a-212f5ea9c78b.png)

It usually works just fine but fails from time to time. Any suggestion that could fix this would be appreciated.

**Comment by sskodje** [comment]
It seems a task was finishing while the task itself was destructed, causing the access violation error. I would check if you have any code flows that could cause the Recorder object to be garbage collected while finishing a recording.

**Comment by peder2key** [comment]
I will check :) Thanks for fast response and a great library 👍
