### ISSUE TITLE
Recorder.GetWindows does not detect borderless windows

### ISSUE THREAD

**Issue by maxthegoof** [sskodje/ScreenRecorderLib#206]
Hi, I have upgraded my vb.net project from your library's previous version, and recorder.getwindows now only detects forms with border, while it was working correctly in version 3.1.2.0. Thanks.

**Comment by sskodje** [comment]
Thanks, i'll investigate. It's probably related to code filtering out un-recordable windows, like the desktop shell.

**Comment by sskodje** [comment]
Fixed with 357c383e1922720340e860f66ce2b946096c6bac
