### ISSUE TITLE
Write error (0x80004005) in video encoder: Erreur non spécifiée If the problem persists, disabling hardware encoding may improve stability.

### ISSUE THREAD

**Issue by DomZZ** [sskodje/ScreenRecorderLib#207]
**Using this recording configuration** :
        RecorderOptions _recordingOptions = new RecorderOptions
        {
            AudioOptions = new AudioOptions
            {
                IsAudioEnabled = false,
                Bitrate = AudioBitrate.bitrate_128kbps, 
                Channels = AudioChannels.Stereo
            },
            VideoEncoderOptions = new VideoEncoderOptions
            {
                //Hardware encoding is enabled by default.
                IsHardwareEncodingEnabled = true,
                //If throttling is disabled, out of memory exceptions may eventually crash the program,
                //depending on encoder settings and system specifications.
                IsThrottlingDisabled = false,
                //Low latency mode provides faster encoding, but can reduce quality.
                IsLowLatencyEnabled = true,
                //Fast start writes the mp4 header at the beginning of the file, to facilitate streaming.
                IsMp4FastStartEnabled = true,
                Quality = 50,
                Framerate = 12,
                IsFixedFramerate = true,
                //Currently supported are H264VideoEncoder and H265VideoEncoder
                Encoder = new H264VideoEncoder
                {
                    BitrateMode = H264BitrateControlMode.Quality,
                    EncoderProfile = H264Profile.Main,
                }
            },
            MouseOptions = new MouseOptions
            {
                IsMousePointerEnabled = false,
                //Displays a colored dot under the mouse cursor when the left mouse button is pressed.	
                IsMouseClicksDetected = true,
                MouseLeftClickDetectionColor = "#FFFF00",
                MouseRightClickDetectionColor = "#FFFF00",
                MouseClickDetectionRadius = 30,
                MouseClickDetectionDuration = 100,
                /* Polling checks every millisecond if a mouse button is pressed.
                   Hook works better with programmatically generated mouse clicks, but may affect
                   mouse performance and interferes with debugging.*/
                MouseClickDetectionMode = MouseDetectionMode.Polling
            }
        };

I get the error with 5.1.1 and upper :
Write error (0x80004005) in video encoder: Erreur non spécifiée If the problem persists, disabling hardware encoding may improve stability.
It works after disabling HardwareEncoding ...

**But with version 5.1 and HardwareEncoding enabled it is working as expected**

**Comment by DomZZ** [comment]
Here is trace file :
[screenrecorderlib.txt](https://github.com/sskodje/ScreenRecorderLib/files/9086806/screenrecorderlib.txt)

My GPU is the one provided with Intel Core i5 7th generation : Intel HD Graphics 620

Thanks

**Comment by rakib33** [comment]
would you please check to disable IsHardwareEncodingEnabled or set it False. IsHardwareEncodingEnabled = False.

**Comment by DomZZ** [comment]
@rakib33 
Here is the log file with option IsHardwareEncodingEnabled set to false.
[screenrecorderlib_hardwareencodingenabled_false.txt](https://github.com/sskodje/ScreenRecorderLib/files/9149594/screenrecorderlib_hardwareencodingenabled_false.txt)

**Comment by gtaoong** [comment]
I also had this problem when I upgraded to 5.1.4

**Comment by DomZZ** [comment]
It seems something change with hardware encoding, I am now able to record a video in 5.2.0.
But only if I comment following settings in MouseOptions :
IsMouseClicksDetected = true,
MouseLeftClickDetectionColor = "#FFFF00",
MouseRightClickDetectionColor = "#FFFF00",
MouseClickDetectionRadius = 30,
MouseClickDetectionDuration = 100

When I keep them I don't see yellow border and video file is very small, video file is playable but content is black for the whole duration.

Note that I'm still using the same computer with the same video card.
Here is the trace log.
[log.txt](https://github.com/sskodje/ScreenRecorderLib/files/10948296/log.txt)
