### ISSUE TITLE
Memory Leak in TestAppWinForms

### ISSUE THREAD

**Issue by peder2key** [sskodje/ScreenRecorderLib#214]
Hello

I am testing the TestAppWinforms and just by looking at the visual studio diagnostic tool it looks like the app i leaking memory: 

The app starts at 26mb and after starting and stopping recording for 5-6 times it goes up all the way to 1.5gb. Any tips?

![Snag_12877198](https://user-images.githubusercontent.com/3829467/201538563-9fd1e4b9-03fe-4004-97f3-918e4d9f7bb4.png)

**Comment by peder2key** [comment]
Interesting. I don't have the problem with memory leaking in the WPF app. But I got a exception when I stopped recording with the winforms app. But not sure if that a clue or not: 

![image](https://user-images.githubusercontent.com/3829467/202646471-45583f6f-ef91-4181-b817-06b8f0dc4111.png)

**Comment by godute** [comment]
Hello, I have the same problem. But I am developing with WPF..
Visual Studio : 2019
ScreenRecordLib : 5.1.4

When I call Recorder.Record, my memory jumps.
And calling Recorder.Stop doesn't decrease memory (Even if I call dispose)

**Comment by peder2key** [comment]
I dont know if this is any help, but I downgraded the nuget package to 5.1.0 and the memory leak was not there anymore.

**Comment by godute** [comment]
wow in my case, I solved at 3.2.0. thank you
![image](https://user-images.githubusercontent.com/31815711/206095418-e720567d-ad96-4acb-97aa-0ec24294fcce.png)

**Comment by sskodje** [comment]
Fixed with 4423c27e1df1e0a92beb9d0c0f8b472dcf94cabb
