### ISSUE TITLE
Getting the stream NALU by NALU to send it through network.

### ISSUE THREAD

**Issue by forlayo** [sskodje/ScreenRecorderLib#217]
I am interested on using the library but to send the capture through network to a remote place, like getting the h264 or h265 nal units and then sending it through RTP. Is this supported? 

I was wondering if passing a stream and reading from it but not sure if it's going to have enough performance..

**Comment by sskodje** [comment]
Hey, sorry for the late reply. It's unfortunately not supported to do what you want, but if you wish to add the functionality, i'm happy to accept a PR :)
