### ISSUE TITLE
The audio and video are not synchronized

### ISSUE THREAD

**Issue by gtaoongood** [sskodje/ScreenRecorderLib#218]
When I chose to record fmp4 for a long time, the generated files, audio and video are out of sync. Audio is faster than video.

**Comment by sskodje** [comment]
I'l look into it. How long did you record to notice this issue?

**Comment by gtaoong** [comment]
Generally more than an hour will appear, the longer the longer the phenomenon is more obvious，but normal MP4 is right.

**Comment by sskodje** [comment]
I believe this issue should be fixed with 323bddf6d03690bf885ce3bd0d15bbe010b9faf2. It would be great if you could test it on your system :)

**Comment by gtaoongood** [comment]
> I believe this issue should be fixed with [323bddf](https://github.com/sskodje/ScreenRecorderLib/commit/323bddf6d03690bf885ce3bd0d15bbe010b9faf2). It would be great if you could test it on your system :)

I'm sorry to find that this problem still exists.

**Comment by sskodje** [comment]
I hope the issue should be properly fixed with 8fc241d9f9c1ffd68b4a87095b25a49b3d2ccbdf. At least i was able to record 7 hours  overnight without any audio drift.

**Comment by gtaoongood** [comment]
> I hope the issue should be properly fixed with [8fc241d](https://github.com/sskodje/ScreenRecorderLib/commit/8fc241d9f9c1ffd68b4a87095b25a49b3d2ccbdf). At least i was able to record 7 hours overnight without any audio drift.

Thank you. That's fine now.
