### ISSUE TITLE
still can not work on windows server 2012 standard

### ISSUE THREAD

**Issue by DNetORM** [sskodje/ScreenRecorderLib#219]
https://github.com/sskodje/ScreenRecorderLib/issues/190

I asked a question before that the component cannot run on Windows Server 2012 well. The author said that it has been fixed, but I tested it with the latest version. The component still cannot run on Windows Server 2012 well, that is, the problem has not been fixed. Has the author tested it?

**Comment by sskodje** [comment]
It's tested to work on Windows Server 2012 R2 and Windows 8.1. On Server 2012 R2, it's required to enable both "Media Foundation" and  "Desktop Experience" windows features. On later OS it's most likely called "Media Features".

**Comment by DNetORM** [comment]
I installed Media Foundation first and then tested it. Visual C++Redistributable x64 has also been installed. If there need any other patches, can you provide the download link? I download it and install it for testing

**Comment by sskodje** [comment]
Did you add "Desktop Experience" windows feature as well?

**Comment by DNetORM** [comment]
The Desktop Experience has also been installed. I directly test it with your winform demo. When I click the record button, an error is reported as follows
System.IO.FileNotFoundException: failed to load file or assembly “ScreenRecorderLib.dll” or one of its dependencies. The specified module could not be found.
filename:“ScreenRecorderLib.dll”
   在 TestAppWinforms.Form1.RecordButton_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)




************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.6.1055.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
TestAppWinforms
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/Administrator/Desktop/Debug/TestAppWinforms.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.6.1055.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.6.1055.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.6.1055.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.33440 built by: FX45W81RTMREL
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.33440 built by: FX45W81RTMREL
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

**Comment by DNetORM** [comment]
And the screen cannot be recorded on win7,  At present, win10 and windows server 2016 are OK, and win7 and windows server 2012 cannot record the screen

**Comment by DNetORM** [comment]
And the screen cannot be recorded on win7, At present, win10 and windows server 2016 are OK, but win7 and windows server 2012 cannot record the screen

**Comment by sskodje** [comment]
Windows 7 is not supported. The necessary Windows API was introduced in Windows 8 and Windows Server 2012.

Windows is a bit of a mess with so many different devices, hardware and versions floating around, but all i can tell you is that i have installed a fresh install of Windows Server 2012 R2, and successfully tested this library to work on it.
