### ISSUE TITLE
[Feature Request] Colored Border

### ISSUE THREAD

**Issue by PikeNote** [sskodje/ScreenRecorderLib#221]
Is there a possibility to allowing the disabling of the colored border the Windows Recorder API automatically puts up for applications that are recorded? 

As per windows docs, [IsBorderRequired](https://learn.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturesession.isborderrequired?view=winrt-20348#Windows_Graphics_Capture_GraphicsCaptureSession_IsBorderRequired) was added and requires a prompt to the user allowing consent of the border to be turned off.

**Comment by sskodje** [comment]
I'll investigate :)

**Comment by dotriz** [comment]
> Is there a possibility to allowing the disabling of the colored border the Windows Recorder API automatically puts up for applications that are recorded?
> 
> As per windows docs, [IsBorderRequired](https://learn.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturesession.isborderrequired?view=winrt-20348#Windows_Graphics_Capture_GraphicsCaptureSession_IsBorderRequired) was added and requires a prompt to the user allowing consent of the border to be turned off.

You can simply add a line of code in StartCapture function in ScreenRecorderLibNative\WindowsGraphicsCapture.cpp like this
`m_session = m_framePool.CreateCaptureSession(m_CaptureItem);`
`m_session.IsBorderRequired(false);`

**Comment by sskodje** [comment]
Added with 5dc52c4f4ec4bf9ea67f8fe60f96f77f83c0e7f5
