### ISSUE TITLE
Sample TestApp & TestAppWinforms executables do not run on Windows 10

### ISSUE THREAD

**Issue by dotriz** [sskodje/ScreenRecorderLib#222]
I we build project and take the contents of bin folder to a Windows 10 22H2 PC, executables do not run.  PC has VC++ runtimes and .Netframework4.7.2 installed. What else needs to be there to make it work?

**Comment by sskodje** [comment]
If it's a normal windows 10 install, you should just need the VC++ runtime. If it's one of the Windows N version, you need to install [media feature pack](https://support.microsoft.com/en-us/topic/media-feature-pack-for-n-editions-of-windows-10-version-1607-b657cb70-33e7-1f11-7119-3b4b50be4e89). If it's Windows Server, then media features must be enabled in role and features manager.

You can use Event Viewer to see the error, if it crashes on launch due to missing dependencies.

**Comment by dotriz** [comment]
Yes, its a normal Windows 10 Pro and VC++ runtime is installed too.

**Comment by sskodje** [comment]
Make sure that if compiled for x64 you must install x64 vc++ runtime, and likewise when compiled for x86 you mist install x86 vc++ runtime. Without more info, i can't really help.

**Comment by dotriz** [comment]
x64 VC++ runtime on a Win10 pro x64 is installed. This is the exact error I get on Windows 10 when I run **Winform project** from this example. WPF project doesn't give any error and doesn't open too.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'ScreenRecorderLib.dll' or one of its dependencies. The specified module could not be found.
File name: 'ScreenRecorderLib.dll'
   at TestAppWinforms.Form1.RecordButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


----- Loaded Assemblies -----
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///F:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
TestAppWinforms
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///F:/Users/mrizw/Downloads/screenrec-win/TestAppWinforms.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///F:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///F:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///F:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///F:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4590.0 built by: NET48REL1LAST_B
    CodeBase: file:///F:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///F:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

----- JIT Debugging -----
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by sskodje** [comment]
>System.IO.FileNotFoundException: Could not load file or assembly 'ScreenRecorderLib.dll' or one of its dependencies. The specified module could not be found.
File name: 'ScreenRecorderLib.dll'

This error usually means a conflict between x86 and x64 dependencies. Check that both the library and the test app is compiled for x64. And if they are compiled for x86, you need to install the vc++ x86 runtime.

**Comment by dotriz** [comment]
Exe and dll are both compiled for x64. And see all x64 VC++ runtimes installed.
![image](https://user-images.githubusercontent.com/4737551/214329240-19b4b809-e91a-4eba-9883-59b312d4a15f.png)

**Comment by sskodje** [comment]
You can try the DLLs from [here](https://github.com/sskodje/ScreenRecorderLib/releases/) or one of the automatic test app builds from [here](https://github.com/sskodje/ScreenRecorderLib/actions/runs/3982221840). If they work, there's something going wrong with the compiling or copying of the files.

**Comment by dotriz** [comment]
I think you are right. That was the issue. Thanks.
