### ISSUE TITLE
Screen recording doesn't stop and gets corrupted 

### ISSUE THREAD

**Issue by ranwer-dev** [sskodje/ScreenRecorderLib#223]
It's completely random, but many times during recording when I press Stop, it doesn't stop recording. Mostly this happens when I am recording audio in and audio out with my desktop. And if I exit the program, the recording will be corrupted and will not play.

These are the options I use for recording

```
RecorderOptions.OutputOptions.RecorderMode = RecorderMode.Video;

RecorderOptions.VideoEncoderOptions.Framerate = 30;
RecorderOptions.VideoEncoderOptions.IsFixedFramerate = true;
RecorderOptions.VideoEncoderOptions.Quality = 80;
RecorderOptions.VideoEncoderOptions.Encoder = new H264VideoEncoder
{
	BitrateMode = H264BitrateControlMode.Quality,
	EncoderProfile = H264Profile.High
};

RecorderOptions.AudioOptions.IsAudioEnabled = true;
RecorderOptions.AudioOptions.IsInputDeviceEnabled = true;
RecorderOptions.AudioOptions.IsOutputDeviceEnabled = true;
RecorderOptions.AudioOptions.AudioInputDevice = (AudioDeviceComboBox.SelectedItem as AudioDevice).DeviceName;
RecorderOptions.AudioOptions.AudioOutputDevice = (SystemAudioDeviceComboBox.SelectedItem as AudioDevice).DeviceName;
RecorderOptions.AudioOptions.InputVolume = 1;
RecorderOptions.AudioOptions.OutputVolume = 1;

RecorderOptions.MouseOptions.IsMousePointerEnabled = true;

RecorderOptions.SourceOptions.RecordingSources = new List<RecordingSourceBase>
	{
		new DisplayRecordingSource(monitor)
		{
			OutputSize = monitor.OutputSize,
			Position = monitor.Position,
			RecorderApi = RecorderApi.WindowsGraphicsCapture,
			IsBorderRequired = false
		}
	};
}
```

**Comment by sskodje** [comment]
It sounds like a hardware encoder issue. I'd try disabling hardware encoder in VideoEncoderOptions to check if the problem goes away. If it's the hardware encoder, updating or reinstalling graphics drivers may fix the issue.

**Comment by ranwer-dev** [comment]
I have added `RecorderOptions.VideoEncoderOptions.IsHardwareEncodingEnabled = false;` but still video recording hung and clicking Finish didn't do anything.

**Comment by ranwer-dev** [comment]
One more instance. I was trying to record a youtube video of 7 minutes, with just the speaker audio, and no mic audio. When I stopped it, it failed :(

Attaching the log here [20230127.log](https://github.com/sskodje/ScreenRecorderLib/files/10521522/20230127.log)

**Comment by ranwer-dev** [comment]
One more. While recording a Youtube video, with both Mic & Speaker audio. In task manage it was taking 7% CPU, suddenly it dropped to less than 1% and when I clicked Finish, it failed to stop. Here's the log file [failed-20230127.log](https://github.com/sskodje/ScreenRecorderLib/files/10521832/failed-20230127.log)

**Comment by sskodje** [comment]
I fixed a couple memory leaks that may be related to your problems, but unfortunately i haven't been able to reproduce it. From your logs, it looks like a complete meltdown in Windows Graphics Capture.

Does it work better if you use Desktop Duplication api?

**Comment by ranwer-dev** [comment]
It happened again. This time with Desktop Duplication. Here is the log [20230204.log](https://github.com/sskodje/ScreenRecorderLib/files/10597876/20230204.log)

I was recording the screen with both mic & speaker sound.

**Mic**
![Microphone Properties 2023-02-04 at 8 43 04 AM](https://user-images.githubusercontent.com/92986100/216746260-00842e4f-25c6-4a4e-b920-4442b1a55c95.png)

**Speaker**
![Speakers Properties 2023-02-04 at 8 43 25 AM](https://user-images.githubusercontent.com/92986100/216746274-97b084c8-f9be-43bc-b15a-2fef74d857bd.png)

**Comment by ranwer-dev** [comment]
Now I just started recording Speaker sound and no mic. But it still hung after almost 3 minutes of recording. Here's log 
[20230204.log](https://github.com/sskodje/ScreenRecorderLib/files/10602432/20230204.log)

**Comment by ranwer-dev** [comment]
Anything else I can do to help you debug this?

**Comment by ranwer-dev** [comment]
I think I can reproduce this every time now. Steps to reproduce
1. Play a youtube video
2. Start recording screen with only Speaker Audio
3. After a few seconds, refresh the page. Youtube will refresh and start playing videos again.
4. After few moments, video gets stuck and will not Finish recording now.

**Comment by sskodje** [comment]
It would be helpful if you can do a failed recording and setting LogOptions with LogSeverityLevel set to Trace. Also, you can open dxdiag.exe and choose the "save all information" option, which should produce a .txt file with your system information.

**Comment by dotriz** [comment]
Here's another failed recording file with trace log
[20230218.log](https://github.com/sskodje/ScreenRecorderLib/files/10772887/20230218.log)

https://user-images.githubusercontent.com/4737551/219827267-6f488886-0a08-4a76-b971-32e080511b53.mp4

**Comment by ranwer-dev** [comment]
Here's another failed recording with the trace log

[20230218.log](https://github.com/sskodje/ScreenRecorderLib/files/10772892/20230218.log)
 
https://user-images.githubusercontent.com/92986100/219827360-edaba4c9-508c-452c-b9ae-8e8826dd79a1.mp4

**Comment by ranwer-dev** [comment]
Now I see the C++ Runtime error when I try to stop the video in the above scenario
![image](https://user-images.githubusercontent.com/92986100/220241070-2c387612-d279-4a98-92e1-f1e40d13b517.png)

Here's the log file
[Log.txt](https://github.com/sskodje/ScreenRecorderLib/files/10789310/Log.txt)

**Comment by sskodje** [comment]
If you click "retry", don't the debugger break at a line, so you get a stack trace? Perhaps check if "enable native code debugging" is enabled under project properties -> debug for the test app.

**Comment by ranwer-dev** [comment]
**enable native code debugging** has worked. It breaks here

```
[[noreturn]] inline void rethrow_exception(_In_ exception_ptr _Ptr) {
    __ExceptionPtrRethrow(&_Ptr);
}
```
Call Stack

>	ScreenRecorderLib.dll!std::rethrow_exception(std::exception_ptr _Ptr) Line 312	C++
 	ScreenRecorderLib.dll!Concurrency::details::_ExceptionHolder::_RethrowUserException() Line 796	C++
 	ScreenRecorderLib.dll!Concurrency::details::_Task_impl_base::_Wait() Line 1622	C++
 	ScreenRecorderLib.dll!Concurrency::task<unsigned char>::wait() Line 3306	C++
 	ScreenRecorderLib.dll!Concurrency::task<void>::wait() Line 4228	C++
 	ScreenRecorderLib.dll!LoopbackCapture::StopCapture() Line 451	C++
 	ScreenRecorderLib.dll!LoopbackCapture::~LoopbackCapture() Line 16	C++
 	[External Code]	
 	ScreenRecorderLib.dll!AudioManager::~AudioManager() Line 14	C++
 	[External Code]	
 	ScreenRecorderLib.dll!RecordingManager::StartRecorderLoop(const std::vector<RECORDING_SOURCE *,std::allocator<RECORDING_SOURCE *>> & sources, const std::vector<RECORDING_OVERLAY *,std::allocator<RECORDING_OVERLAY *>> & overlays, IStream * pStream) Line 756	C++
 	ScreenRecorderLib.dll!RecordingManager::BeginRecording::__l2::<lambda>() Line 243	C++
 	[External Code]	
 	[Async Call]	
 	ScreenRecorderLib.dll!RecordingManager::BeginRecording(std::wstring path, IStream * stream) Line 230	C++
 	ScreenRecorderLib.dll!RecordingManager::BeginRecording(std::wstring path) Line 192	C++

**Comment by sskodje** [comment]
I added some more error handling, it should hopefully stop the crashing.

**Comment by ranwer-dev** [comment]
I have tried several recordings and unable to reproduce the issue. It seems to be working fine now 👍
