### ISSUE TITLE
Remove dependency check for windows media foundation

### ISSUE THREAD

**Issue by hakito** [sskodje/ScreenRecorderLib#227]
The dependency check for the registry key probably never applies. If MF is missing we already get a FileNotFoundException during loading from ScreenRecorderLib.dll.

TLDR

The check for the registry key at https://github.com/sskodje/ScreenRecorderLib/blob/master/ScreenRecorderLibNative/RecordingManager.cpp#L837 [only applies to windows 8 N and KN](https://learn.microsoft.com/en-us/windows/win32/medfound/about-the-media-foundation-sdk) according to the documentation. But it also applies to Win 10 N (see below) The [extended support for 8.1 ended January 2023](https://learn.microsoft.com/de-de/lifecycle/products/windows-81).

The registry key is only present (on windows 10) when the windows features _Media Features_ *and* _Windows Media Player_ are installed. But screen recording works also when those features are not installed.

I also tested it in _Windows Server 2012 R2_. The check also prevents recording. I recompiled it without the check and the screen recording was working properly.

So this check also fails if Media Foundation is present on the system.

I also tested it in Windows 10 Pro N. The console app instantly crashes on startup:

> Unbehandelte Ausnahme: System.IO.FileNotFoundException: Die Datei oder Assembly "ScreenRecorderLib.dll" oder eine Abhängigkeit davon wurde nicht gefunden. Das angegebene Modul wurde nicht gefunden.
>    bei TestConsoleApp.Program.Main(String[] args)

Using process monitor with sysinternals indicates that MF is also missing for that OS. (MF.dll not found). But this exception occurs already during type loading. After installing Media Feature Pack it was working properly.

**Comment by sskodje** [comment]
Looks good, thank you :)
