### ISSUE TITLE
VB.net nothing from capturing Windows

### ISSUE THREAD

**Issue by nico579** [sskodje/ScreenRecorderLib#229]
Hello,

I am using VB.net and want to record from a Window.
Here is my code :

Dim  _re As Recorder
Dim so As New SourceOptions
Dim rs As New List(Of RecordingSourceBase)
Dim ro As New RecorderOptions
Dim rw = Recorder.GetWindows()

rs.Add(rw.FirstOrDefault())
so.RecordingSources = rs
ro.SourceOptions = so
_re = Recorder.CreateRecorder(ro)
_re.Record("c:\aa.mp4")

No error, but no file is created !

have an explain ?

Thanks a lot

**Comment by sskodje** [comment]
You can subscribe to the OnRecordingFailed event to see the error. But i can guess that you need to run your application with administrator prvileges to write to c:\ root. Or write to a path in the Users directory instead.

**Comment by nico579** [comment]
Thanks a lot !!!
The error was : "Windows Graphics Capture requires Windows 10 version 1903 or greater." !!!
It is OK with monitor, but failed with Windows ...
Your library is very nice !!!
