### ISSUE TITLE
Downscaling video

### ISSUE THREAD

**Issue by ranwer-dev** [sskodje/ScreenRecorderLib#232]
is it possible that we downscale a recording? Like if we are recording a large screen but it saves out to a 720p resolution to save disk space?

**Comment by sskodje** [comment]
Yes, either with [OutputOptions](https://github.com/sskodje/ScreenRecorderLib/wiki/Quickstart-guide-v5.x.x#change-the-options-with-recorderoptions) or by the individual [source options](https://github.com/sskodje/ScreenRecorderLib/wiki/Quickstart-guide-v5.x.x#source-properties)
