### ISSUE TITLE
Starting recording with initial Paused state

### ISSUE THREAD

**Issue by ranwer-dev** [sskodje/ScreenRecorderLib#233]
Is it possible to start the recording in a paused state? So that it initializes all the components and can immediately resume when the Pause state is changed later? This can be helpful to ensure that initial moments are not missed in the recording.

**Comment by sskodje** [comment]
With c0afe3fa29bb8b972cb0465c6a9727fa15455179 you should be able to pause from the start, by calling Pause() directly after Record()
