### ISSUE TITLE
Very high GPU usage

### ISSUE THREAD

**Issue by ranwer-dev** [sskodje/ScreenRecorderLib#236]
I have seen 1920x1080 screen recordings, without audio and with quality 70 and framerate 30, which takes almost 8% CPU & 30% GPU on my laptop. Whereas if I record the screen using FFmpeg, it takes 8% of CPU only, with No GPU used at all.

Why is this? Can we reduce GPU usage?

**Comment by sskodje** [comment]
I'll run some profiling and see

**Comment by sskodje** [comment]
Yeah, it should be fixed in one of the recent commits.
