### ISSUE TITLE
can not work on windows server 2016 datacenter

### ISSUE THREAD

**Issue by liku-king** [sskodje/ScreenRecorderLib#238]
i have installed "Media Foundation" in Server Manager, and the event OnRecordingFailed show "Windows Graphics Capture requires Windows 10 version 1903 or greater." error

**Comment by sskodje** [comment]
Windows Graphics Capture is the most modern screen recording API in Windows, and requires Windows 10 version 1903 or greater. This means it will only work on Windows Server 2019 or newer. For Server 2016, Desktop Duplication API should work.

**Comment by liku-king** [comment]
thanks, and i wanna recording window on server 2016 so this lib is not supporting now
