### ISSUE TITLE
question: how to resolve You need to specify platform (x86, Win32 or x64). 

### ISSUE THREAD

**Issue by PavanMudigondaTR** [sskodje/ScreenRecorderLib#246]
Hi, I am trying to use ScreenRecorderLib in Selenium C# and I am getting this error and I am not sure how to resolve it.

Error:

D:\Users\xxxxxxxx\.nuget\packages\screenrecorderlib\5.2.0\build\ScreenRecorderLib.targets(6,5): error : ScreenRecorderLib does not work correctly on 'AnyCPU' platform. You need to specify platform (x86, Win32 or x64). [D:\xxxxxxx\VOTestAutomation\VOTestAutomation.csproj]

**Comment by sskodje** [comment]
The error is because c++ does not supported "Any CPU" compile platform, like c# does.

**Comment by PavanMudigondaTR** [comment]
thanks it works now with x86
