### ISSUE TITLE
not compatible with vs 2022

### ISSUE THREAD

**Issue by aqibbanday** [sskodje/ScreenRecorderLib#247]

**Comment by sskodje** [comment]
I'm going to need some more information here. What isn't compatible with vs 2022?

**Comment by aqibbanday** [comment]
> I'm going to need some more information here. What isn't compatible with vs 2022?

Project isn't working in vs2022 without retargetting

**Comment by sskodje** [comment]
You may need to install the correct Windows SDK or .net framework  in visual studio installer.
