### ISSUE TITLE
Feature Request: Adding padding on all sides of video with a background image

### ISSUE THREAD

**Issue by ranwer-dev** [sskodje/ScreenRecorderLib#250]
When we record a window, it will look better if we can add padding on all sides and use a background image for that area.
Like **Without Padding**

https://github.com/sskodje/ScreenRecorderLib/assets/92986100/5923a392-627e-45f3-8dee-97a7ac249613

**With Padding**

https://github.com/sskodje/ScreenRecorderLib/assets/92986100/b88e3e4d-dbf8-48a1-99a9-a63d378c4063

**Comment by sskodje** [comment]
This can be done by setting an image as the recording source, then adding a window recording with offset as an overlay on it.
