### ISSUE TITLE
How to show camera preview?

### ISSUE THREAD

**Issue by Praveen-Jeffri** [sskodje/ScreenRecorderLib#252]
I am implemented the camera recording and it is working good , don't know how to show the preview , please help me with that

**Comment by sskodje** [comment]
There's no functionality for previewing cameras in this library, but perhaps you can use the windows community toolkit. I haven't tested it myself though, but worth a shot. https://learn.microsoft.com/en-us/windows/communitytoolkit/controls/camerapreview
