### ISSUE TITLE
Need Help!!!

### ISSUE THREAD

**Issue by Praveen-Jeffri** [sskodje/ScreenRecorderLib#253]
How to make the mouse pointer disable in selective window recording ? when i did this it also showing up in output video

**Comment by sskodje** [comment]
There's a bug where the global toggle in mouse options does not affect window recordings, but you can also disable it with the IsCursorCaptureEnabled property on the RecordingSource itself.

Also it's quite frowned upon in the open source community to start an issue with things like "need help!!!!". You don't need help, you want help. And the people who may wish to help, want a descriptive title on their issues.
