### ISSUE TITLE
Exclude one window from recording

### ISSUE THREAD

**Issue by k1mmm** [sskodje/ScreenRecorderLib#259]
Hello! Does the source options support adding multiple windows? 

My goal is trying to exclude one window from the recording (in my case the recording controls itself) but I'm getting the error "wrongfully params" when starting the recording.

My idea was to add the screen and all windows but exclude my recording controls window to the RecordingSources list.

**Comment by k1mmm** [comment]
@ranwer-dev It worked, thank you!

**Comment by sskodje** [comment]
You can also call it like this to exclude the current window:
         
```csharp 
IntPtr hwnd = new WindowInteropHelper(this).Handle;
Recorder.SetExcludeFromCapture(hwnd, true);
```

To include it again, call the same with "false" as param.
