### ISSUE TITLE
A procedure imported by 'ScreenRecorderLib.dll' could not be loaded.

### ISSUE THREAD

**Issue by SaddamBInSyed** [sskodje/ScreenRecorderLib#26]
How do I make this  **ScreenRecorderLib.dll is work with Windows 7.**  both 32 and 64 bit.

I am getting an exception like below **A procedure imported by 'ScreenRecorderLib.dll' could not be loaded.**

please advice

**Comment by sskodje** [comment]
Unfortunately you do not. This library requires Windows 8 or higher to function, due to the [Desktop Duplication API](https://docs.microsoft.com/en-us/windows/desktop/direct3ddxgi/desktop-dup-api) only being available in Windows 8 and newer.

**Comment by SaddamBInSyed** [comment]
Thanks for reply.

whether I need to install any extra package in  win 8 / /10 pcs to run this library.

please advise

**Comment by sskodje** [comment]
It's explained in the Readme.
