### ISSUE TITLE
Recording the secondary screen

### ISSUE THREAD

**Issue by HPBotma** [sskodje/ScreenRecorderLib#264]
Hi - I can't seem to get the library to record the second screen? [Screen connected to my laptop via HDMI].

It records the primary screen fine, but if I select only the second screen for recording - it throws an exception "The parameter is incorrect".  

If I choose to record both screens simultaneously, I get no errors, but on playback, there is a blank spot where the second display should be.   

i use the snippet from the example project to configure the sources: 
     RecorderOptions options = new RecorderOptions
                {
                    SourceOptions = new SourceOptions
                    {
                        RecordingSources = sources
                    }
                };
                _rec = Recorder.CreateRecorder(options);

![screenlib issue](https://github.com/sskodje/ScreenRecorderLib/assets/29191973/a6e40abe-5180-4517-9a0e-28a6a9d77990)

Not sure why the second screen is called display 4 [see image]  - as there is nothing else connected?  Any advice would be greatly appreciated

**Comment by sskodje** [comment]
Does it work if you swap the recorder API from Desktop Duplication to Windows Graphics Capture? Desktop duplication is older, and have known issues with laptops with both integrated graphics and discrete graphics.

**Comment by HPBotma** [comment]
Thanks for the quick response!  However, I am not sure where to change the recorder API ?  the example project does not seem to  make any mention of it?

**Comment by sskodje** [comment]
It's the property RecorderApi on the DisplayRecordingSource object.

**Comment by HPBotma** [comment]
Great - works well! Thanks for all the effort in creating and maintaining this library

**Comment by kasirajansfm** [comment]
`SourceOptions = new SourceOptions { 
    RecordingSources = { 
        new DisplayRecordingSource { 
            DeviceName = DisplayRecordingSource.MainMonitor.DeviceName,RecorderApi = RecorderApi.WindowsGraphicsCapture 
        } 
    } 
},`

added this option but still records main monitor only, anyone facing same?
