### ISSUE TITLE
taking screenshot

### ISSUE THREAD

**Issue by mal1ceee** [sskodje/ScreenRecorderLib#266]
is it possible to add an option to allow taking screenshots on click instead of interval?

**Comment by sskodje** [comment]
Do you mean while recording a video?

**Comment by mal1ceee** [comment]
yes, currently the screenshot is taken in interval, is there any built in features that allow screenshot to be taken on click or do i have to add logic so it takes one single screen on click

**Comment by sskodje** [comment]
No unfortunately not.

**Comment by mal1ceee** [comment]
Will there be future implementing of it ?

**Comment by sskodje** [comment]
I'm sorry for the late reply, been very busy lately. I just had a quick glance at the code, and it doesn't look very difficult to implement. I'll try to get it done in the coming weeks.

**Comment by mal1ceee** [comment]
Thank you appreciate it :)

**Comment by mal1ceee** [comment]
hello, i was wondering if there is any update regarding this

**Comment by sskodje** [comment]
I added the functionality to the main branch. Let me know if you have any issues :)

**Comment by mal1ceee** [comment]
thanks for adding the feature, you are a lifesaver but i was wondering if its possible to update nuget packages to include the screenshot, cant access them ;o

**Comment by sskodje** [comment]
It's up now.

**Comment by mal1ceee** [comment]
Thanks for helping, i realised that the screenshot does not have the options to change the quality or the window it was suppose to take, i was wondering if that could be added in also :D SORRY FOR ALL THESE ISSUE :(

**Comment by sskodje** [comment]
No that's not possible. If you want to reencode, you can use e.g. ImageFlow.

**Comment by mal1ceee** [comment]
what about choosing what to screenshot ?

**Comment by sskodje** [comment]
I'm afraid i don't understand the question. The snapshot is the same as the recording sources, i.e. the same as the video output.
