### ISSUE TITLE
Record() after Pause() bug

### ISSUE THREAD

**Issue by MihailSklyarenko** [sskodje/ScreenRecorderLib#268]
I noticed a problem with the fact that if, after a pause, you call the Record method on the recorder and pass arbitrary parameters there, recording will continue to the same file/stream that was originally opened.
Was it intended to be able to record to different files with one recorder?

![изображение](https://github.com/sskodje/ScreenRecorderLib/assets/69673463/3fe42e14-fbf0-421c-bc46-9330b79e02e1)

**Comment by sskodje** [comment]
This is working as intended. Pausing just pauses the current recording, so you have a gap of time in it while paused. If you want to reuse the recorder, you must stop it first, and wait for the recording to finalize.
