### ISSUE TITLE
Additional Folder created when recording to path

### ISSUE THREAD

**Issue by AdamMurray1** [sskodje/ScreenRecorderLib#272]
This one is pretty straightforward.  When recording to a path an additional directory with the file name is being created.  This output is seen with all default settings and running "TestApp" currently packaged with ScreenRecorderLib.  I was also seeing the same behavior on my own project.

![image](https://github.com/sskodje/ScreenRecorderLib/assets/112960525/c6b7e35f-ff09-496c-b586-1ed6b0514cc5)

**Comment by tamasbito99** [comment]
Hi! I also encountered this problem in the latest Nuget version (5.4.0). I would like to ask approximately when the version with this bugfix is ​​expected?

**Comment by sskodje** [comment]
I pushed a new release now.
