### ISSUE TITLE
Publishing a singel file breaks the assembly for this library.

### ISSUE THREAD

**Issue by JanssonTheBest** [sskodje/ScreenRecorderLib#274]
**I recently tried publishing my project as a single file, by merging all the assemblies into to one exe, where I've used x86 on everything, but the screenrecorderlib assembly breaks.**

System.BadImageFormatException
  HResult=0x8007000B
  Message=Could not load file or assembly 'ScreenRecorderLib, Version=1.0.8721.22425, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.
  

  This exception was originally thrown at this call stack:
    System.Runtime.Loader.AssemblyLoadContext.InternalLoad(System.ReadOnlySpan<byte>, System.ReadOnlySpan<byte>)
    System.Reflection.Assembly.Load(byte[], byte[])
    System.Reflection.Assembly.Load(byte[])
    Costura.AssemblyLoader.ReadFromEmbeddedResources(System.Collections.Generic.Dictionary<string, string>, System.Collections.Generic.Dictionary<string, string>, System.Reflection.AssemblyName) in Common.cs
    Costura.AssemblyLoader.ResolveAssembly(object, System.ResolveEventArgs) in ILTemplate.cs
    System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(System.ResolveEventHandler, System.Reflection.RuntimeAssembly, string)
    System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(System.Reflection.RuntimeAssembly, string)

Inner Exception 1:
BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)

**Comment by sskodje** [comment]
Unfortunately, to my knowledge, single file deployment does not work with libraries compiled with c++/cli.

https://github.com/dotnet/sdk/issues/12345

**Comment by JanssonTheBest** [comment]
> Unfortunately, to my knowledge, single file deployment does not work with libraries compiled with c++/cli.
> 
> https://github.com/dotnet/sdk/issues/12345

Any idea where i could start researching? What exactly is the issue, why cant I merge everything into one assembly?

**Comment by sskodje** [comment]
It's an issue with the dot net build tools apparently. I don't know any more unfortunately.

**Comment by JanssonTheBest** [comment]
![image](https://github.com/sskodje/ScreenRecorderLib/assets/118405460/ab8aa341-4d8c-42c3-a55d-f18717074b0e)
How would I do this?

**Comment by D0nw0r** [comment]
> > https://learn.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-in-visual-studio
> 
> I solved the problem through selfextracting and .net reflection

Can you share your solution for this? I am running into the same problem and cant find a way :\

**Comment by JanssonTheBest** [comment]
> > > https://learn.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-in-visual-studio
> > 
> > 
> > I solved the problem through selfextracting and .net reflection
> 
> Can you share your solution for this? I am running into the same problem and cant find a way :\

Sure I published my way of solving it here:

https://github.com/dotnet/sdk/issues/12345#issuecomment-1950085253
