### ISSUE TITLE
Feature Request: Can we use this library to only record audio from mic & speaker?

### ISSUE THREAD

**Issue by ranwer-dev** [sskodje/ScreenRecorderLib#279]
Can this library be modified in a way that it supports only audio recording? I mean no screen recording, just output the audio from the mic & speaker.

**Comment by sskodje** [comment]
You can turn off the video input, but it will be a black screen video with audio, not an audio file.

**Comment by Willy-Kimura** [comment]
Not possible at the moment.
Looks like the `OutputOptions.IsVideoCaptureEnabled` property is not working.

**Comment by rwedoff** [comment]
Also note, Overlay options shouldn't be set then as well.
