### ISSUE TITLE
Are there any minimum system requirements for this to work? 

### ISSUE THREAD

**Issue by electleaf** [sskodje/ScreenRecorderLib#282]

**Comment by sskodje** [comment]
This library at minimum requires Windows 8 or higher to function, as well as [Visual C++ Redistributable x64](https://aka.ms/vs/16/release/vc_redist.x64.exe) or [Visual C++ Redistributable x86](https://aka.ms/vs/16/release/vc_redist.x86.exe) installed, depending on platform compiled for. Some features like WGC requires windows 10. Hardware acceleration require compatible hardware. HEVC require compatible hardware or [software encoder from microsoft store.
](https://apps.microsoft.com/detail/9NMZLZ57R3T7?hl=en-us&gl=US)

This library also requires Media Foundation to work, which have to be installed from Server Manager if run on Windows Server, or from the respective "Media Feature Pack" if run on a Windows N or KN version.
