### ISSUE TITLE
Set the border's color around of the recording DisplayOverlay

### ISSUE THREAD

**Issue by tamasbito99** [sskodje/ScreenRecorderLib#285]
Would it be possible to change the yellow border around the current DisplayOverlays? (For example change it to red color just like in Skype.)

It would also be great if this border could be placed around the DisplayRecordingSource passed in the RecordingSourceBase.

**Comment by aqibbanday** [comment]
I don't think the border can be changed, you can instead try deaktopduplication method

**Comment by sskodje** [comment]
If you mean the yellow border that is shown around windows or screens, that is a Windows feature to let the user show what is being recorded, and not part of this library. I don't know what skype does, but I don't think you can change it's color.
