### ISSUE TITLE
Recording does not start when stop on paused

### ISSUE THREAD

**Issue by ybbahg** [sskodje/ScreenRecorderLib#286]
Hi
I was using 5.1 of engine.
RecordingManager::EndRecording() clear for m_IsPaused
but 6.0.0 does not clear
then when I stop recording on paused status
this value is still remained as 'true'
So even I tried to restart recording, it could not start but paused.
I know TestApp calls CleanupResources() to dispose engine
but I prefer reuse already created engine.
thanks

**Comment by sskodje** [comment]
Thanks for reporting! I have fixed it and will push soon.
