### ISSUE TITLE
Support for Captions/Video Transcript

### ISSUE THREAD

**Issue by rwedoff** [sskodje/ScreenRecorderLib#288]
Do you have support for Windows Speech Recognizer for captions for the video? Could this be exposed via recording options as another output?
https://learn.microsoft.com/en-us/uwp/api/windows.media.speechrecognition.speechrecognizer?view=winrt-22621

**Comment by sskodje** [comment]
There's no support for that. If what you are after is to burn text into the video like permanent captions, you can probably implement it as an overlay and modify one of the existing ones. If you are after the text directly, it's probably easier to implement it in your own app from the audio source directly.

**Comment by rwedoff** [comment]
Thanks for the quick response!
