### ISSUE TITLE
Weird errors that occur immediately upon starting the recording

### ISSUE THREAD

**Issue by Duke02** [sskodje/ScreenRecorderLib#29]
Hello! Recently I've been getting some errors while using this library. I have recently updated to the latest Windows Update ([KB4499167](https://support.microsoft.com/en-us/help/4499167/windows-10-update-kb4499167)) so that might be a cause. 

The errors I am getting happen immediately after starting to record but before the recorder object goes into the Recording state. The error messages are as follows:
* The data specified for the media type is invalid, inconsistent, or not supported by this object.
* The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action. 

Everything seems to be mostly in line with proper initiation (most of my code came from the example code on the README). Do you know what may have possibly caused this to occur?

Thank you and have a nice day!

**Comment by sskodje** [comment]
Hey!

That error means the graphics drivers have encountered a problem. It's really hard to say what's the cause, it looks like it can be anything from bad drivers to overheating, overclocking, hardware faults..

This library only calls on Windows API's, and i really doubt there is anything you can do wrong in your code, to cause such an error either.

**Comment by Duke02** [comment]
Well recently our program has been having out of memory errors. Would that be a potential cause?

**Comment by sskodje** [comment]
I don't know. It's not an error i have experienced myself.

**Comment by Duke02** [comment]
@sskodje sorry for getting back to you so late. We're thinking that it may just be something to do with our application, seeing as it is rather large. We don't seem to be detecting significant memory leaks after updating our application to 64 bit. Thank you for your help nonetheless!
