### ISSUE TITLE
All Monitor Recording Not Working

### ISSUE THREAD

**Issue by kasirajansfm** [sskodje/ScreenRecorderLib#295]
`SourceOptions = new SourceOptions {  RecordingSources = {  new DisplayRecordingSource {  DeviceName = DisplayRecordingSource.MainMonitor.DeviceName,RecorderApi = RecorderApi.WindowsGraphicsCapture  }  }  },`

After changed RecorderApi.WindowsGraphicsCapture, still records first screen only. any one faced this issue,?

**Comment by sskodje** [comment]
Your code is only recording the main monitor. If you want to record all monitors:

```csharp
            var sources = new List<RecordingSourceBase>();
            //You can all system monitors with the static Recorder.GetDisplays() function.
            sources.AddRange(Recorder.GetDisplays());
```

**Comment by kasirajansfm** [comment]
Thanks for the response. Its working fine.
