### ISSUE TITLE
Error: AcquireNextFrame error: The keyed mutex was abandoned.

### ISSUE THREAD

**Issue by aaryamanc** [sskodje/ScreenRecorderLib#30]
Hello Sverre

I'm on win10 with all the updates with VS2019 and seeing following error every now and then, have you ever encountered this issue or know what could be the reason? I did display driver update today along with windows update. Also, i took the latest code from the repo and compiled it onto local machine ( exhibiting this issue ) and used the generated lib to rule out any dependency issue. 

00000037	1.33105326	[16460] Wrote frame with start pos 51011 ms and with duration 33 ms	
00000038	1.36531556	[16460] Wrote frame with start pos 51045 ms and with duration 37 ms	
00000039	1.53500974	[16460] Wrote frame with start pos 51082 ms and with duration 169 ms	
00000040	1.56823719	[16460] Wrote frame with start pos 51252 ms and with duration 33 ms	
00000041	1.99900198	[16460] Wrote frame with start pos 51285 ms and with duration 417 ms	
00000042	2.03447485	[16460] Error: AcquireNextFrame error: The keyed mutex was abandoned.	
00000043	2.03447485	[16460] 	
00000044	2.03449488	[16460] Error: RETURN_ON_BAD_HR: Access is denied.	
00000045	2.03456140	[16460] Error: Reinitialized desktop duplication error: Access is denied.	
00000046	2.03456140	[16460] 	
00000047	2.03645086	[16460] Error: AcquireNextFrame error: Access is denied.	
00000048	2.03645086	[16460] 	
00000049	2.03653789	[16460] Error: RETURN_ON_BAD_HR: Access is denied.	
00000050	2.03655386	[16460] Error: Reinitialized desktop duplication error: Access is denied.	

In addition, when this issue happens, i see following assertion message:

![image](https://user-images.githubusercontent.com/49593916/59328367-0bf8f880-8ca1-11e9-90c5-7f9d54caec49.png)

Thanks

**Comment by sskodje** [comment]
"The keyed mutex was abandoned" is the error message given for the error code "DXGI_ERROR_ACCESS_LOST". From the [documentation](https://docs.microsoft.com/en-us/windows/desktop/api/dxgi1_2/nf-dxgi1_2-idxgioutputduplication-acquirenextframe), this means the current desktop is invalidated by something, usuall a fullscreen application, desktop switch etc. When this happens, the Desktop Duplication instance is immediately recreated.

What happens in your case is that the Desktop Duplication instance can not be recreated, as you get an Access is denied error. The [documentation](https://docs.microsoft.com/en-us/windows/desktop/api/dxgi1_2/nf-dxgi1_2-idxgioutput1-duplicateoutput) says E_ACCESSDENIED will be returned if you do not have access privileges to the desktop image, but i'm not entirely sure what that means.

The debug assertion complains about a smart pointer being undefined, but that's not related.

**Comment by aaryamanc** [comment]
Thanks. This happens when we run  automation and launch edge browser using selenium. Our flow is - unit test we start recording video; launch web browser, stop video ; close web browser. We create recorder everytime for each test case and then deletes it. If I keep only 1 instance of recorder; do you think it will resolve the issue?

**Comment by sskodje** [comment]
No, the issue is with the access to Windows' DirectX API's. In essence you are denied access to the graphics card output. I have not had any similar issues, so it's hard to say. It's most likely related to graphics drivers, and i see some have problems with [hybrid systems](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/using-cross-adapter-resources-in-a-hybrid-system) (using both integrated and dedicated graphics)

**Comment by aaryamanc** [comment]
It was a silly mistake on my part, i was starting the test run through Remote Desktop (RDP) and then as the run starts i disconnected the RDP session which was causing the recording to fail as there is no desktop to record.
