### ISSUE TITLE
Audio device changed may kill application

### ISSUE THREAD

**Issue by ybbahg** [sskodje/ScreenRecorderLib#300]
Hi @sskodje 

I'd like to report an issue that application crash
ScreenRecorderLibNative::CoreAudio.util contains 
`HRESULT GetAudioDeviceFriendlyName(_In_ IMMDevice *pDevice, _Out_ std::wstring *deviceName){...}`
and varString.pwszVal might be NULL
so `*deviceName = std::wstring(varString.pwszVal);` might go crash
Not all my machines but several ones have this issue.
So NULL check may need

thanks

**Comment by sskodje** [comment]
Thanks for letting me know, i'll add a null check
