### ISSUE TITLE
Can watermark support be added

### ISSUE THREAD

**Issue by xuechenga** [sskodje/ScreenRecorderLib#301]
Can watermark support be added

**Comment by sskodje** [comment]
https://github.com/sskodje/ScreenRecorderLib/wiki/Quickstart-guide-v5.x.x#add-overlays-to-recording

You can use a video file or GIF for animated, or a JPEG or PNG. Use PNG if you want semi transparent.

**Comment by xuechenga** [comment]
Thank you for your answer
