### ISSUE TITLE
Overlay Issue [Error 0x80004002]

### ISSUE THREAD

**Issue by Landstalker1313** [sskodje/ScreenRecorderLib#306]
Hello sskodje,
First, I would like to thank you for your great job. you library is awesome !

I have a small issue when adding "Window Overlay", The Window of the Destination Application is OK, at ScrennRecorder Application level, the handle of the Destination Window is OK also. 

I enabled the logs, and the lib says ;
 
[INFO]  [RecordingManager.cpp     |         operator (): 284] >> Starting recording task
[ERROR] [WindowsGraphicsCapture.c |      GetCaptureItem: 356] >> Failed to create capture item for window: error is No such interface supported
[ERROR] [ScreenCaptureManager.cpp | ProcessCaptureHRESU:1322] >> Unexpected error, aborting capture: hr = 0x80004002, error = No such interface supported
[ERROR] [ScreenCaptureManager.cpp | OverlayCaptureThrea:1204] >> Fatal error in overlay capture, exiting..
[INFO]  [OutputManager.cpp        |   FinalizeRecording: 133] >> Cleaning up resources

Do you have any suggestion please ?
Thank you

**Comment by sskodje** [comment]
Hi! My experience is that not all windows can be captured, for various reasons. I can be due to directx if it's a game window, or DRM, or UAC protection, or things like that. Can you record the window as a recording source, not as an overlay, and can you record other windows, like for example a File Explorer window?

**Comment by Landstalker1313** [comment]
Hello sskodje,
Thanks for your response.

My code (with overlay) works very fine on some machines, but not working on some other ones, even if I install all prerequisites ( Visual C++ Redistributable, .NET, ...).

The destination application (source of Overlay) is a simple Winform application.

I didn't test a Window as recording source, but the current code works perfectly (Window as Overlay) on my computer (and not on another one)

Is theire some speciale package to install in addition to ( Visual C++ Redistributable, .NET, ...) ? for example : WinRT, Special SDK, ... ?

Thank you very much

**Comment by saman1832** [comment]
@Landstalker1313 does this overlay code will help to record a tab that us pooed out from main window?
I think you managed to use overlay feature so just confirming.

**Comment by Landstalker1313** [comment]
Hello @saman1832 

Thanks for support.

The use of the overlay in my case is just to have a timestamp on the video. For this, the overlay source window is a simple WinForm which displays the local time which will evolve throughout the recording. thus, each Frame will be associated with a Timestamp.

Why this need? because I record 3 screens with 3 ScreenRecorder EXE (3 processes), and I want to prove that the three videos are synchronized using the timestamp provided by the Overlay window.

If there is an option to add a timestamp to the video (not just recording start time but current time) I am interested and it will allow me to get around this problem.

Have a nice day

**Comment by sskodje** [comment]
You can add a timestamp using an image overlay that you update periodically. I don't have the time to make a sample code now, but i'll post it here sometime later in the weekend.

**Comment by Landstalker1313** [comment]
Hello ssKodje,
Thanks for support.

I saw an example in your code (WPF project), I will try to do it :)

Thanks

**Comment by sskodje** [comment]
Ok, there is also a known bug where the overlay can flicker when updating. I'm working on a fix, if you experience it🙂
