### ISSUE TITLE
Capture the pop out tab from window.

### ISSUE THREAD

**Issue by saman1832** [sskodje/ScreenRecorderLib#307]
I have a wpf application in which h have multiple tab and if I pop the tab out the pop out tab is not getting recorded.
Or if any popup is opened that is not getting recorded as that is different window I guess. can we fix this?

**Comment by sskodje** [comment]
Yes, it's because it's a different window. I recommend recording the entire desktop in this scenario.

**Comment by saman1832** [comment]
Actually the use case is we don't want to record full dekstop . So, will cropped desktop will not do full desktop recording?
And how we do it?

**Comment by saman1832** [comment]
@sskodje can you please let me know how we can do cropped desktop recording?

**Comment by sskodje** [comment]
Either globally on the entire output via the output options: https://github.com/sskodje/ScreenRecorderLib/wiki/Quickstart-guide-v5.x.x-and-newer.#change-the-options-with-recorderoptions

Or by configuring the source: https://github.com/sskodje/ScreenRecorderLib/wiki/Quickstart-guide-v5.x.x-and-newer.#source-properties

**Comment by saman1832** [comment]
@sskodje Thnks for the update. Can we also change the sourceRect dynamically?

**Comment by sskodje** [comment]
Yes, using DynamicOptionsBuilder.

**Comment by saman1832** [comment]
@sskodje I tried dynamicoption and it's working perfectly. thnks for the great work

Can we also record specific any two or three windows by passing the window handle or name?

**Comment by sskodje** [comment]
Yes. If you want them next to the desktop (side by side) add WindowRecordingSource, if you want them overlayed, use WindowOverlay.

**Comment by sskodje** [comment]
I see. There are currently some limitations that is in the way for your use case. I'm working on a fix, but here is a workaround in the mean time.

The overlays need to be added before starting the recording, and the recording has to be started (RecordingStatus = Recording) before applying dynamic options. Unfortunately there is also missing a property from the overlay to disable it from the start. This means you need to add a window overlay with a **valid window handle**, with for example size 1x1px, listen for OnStatusChanged change, call

```csharp
rec.GetDynamicOptionsBuilder()
.SetVideoCaptureEnabledForOverlay(MyOverlay.ID, false)
.Apply()
```
to disable overlay recording temporarily when statis is Recording. Now the overlay lies dormant and can be used later. When you need it, update MyOverlay object with the Window handle  and other info you want, and call

```csharp
rec.GetDynamicOptionsBuilder()
.SetUpdatedOverlay(MyOverlay)
.SetVideoCaptureEnabledForOverlay(MyOverlay.ID, true)
.Apply()

**Comment by sskodje** [comment]
Added support for inserting overlays during a recording in progress with d016a24. Now you can simply call SetUpdatedOverlay() with a new overlay.
