### ISSUE TITLE
Use to screen catch in remote desktop

### ISSUE THREAD

**Issue by thunderDAO-amin** [sskodje/ScreenRecorderLib#308]
When i use it in the remote desktop to screen catch by RDS, but when the rds link broken, then the screen catch stop. Why and how to solve it?

**Comment by sskodje** [comment]
As far as i know, remote desktop sessions are virtual desktops only rendered when the user is connected. When the user disconnects, the user is logged out and there is no video output to record.

**Comment by thunderDAO-amin** [comment]
thank you , as you know,  is there a solution ?
