### ISSUE TITLE
Snapshot frame is not refreshed on paused status

### ISSUE THREAD

**Issue by ybbahg** [sskodje/ScreenRecorderLib#309]
Hello
Current recorder loop checks m_IsPaused value before AcquireNextFrame
so when we take screenshot on paused status, captured frame is old one
I suggest check m_IsPaused value 'after' AcquireNextFrame to refresh current captured frame
thanks

**Comment by sskodje** [comment]
Do you mean when calling TakeSnapshot() ?

**Comment by ybbahg** [comment]
@sskodje Yes you're right.

Try take snap shot when recording is paused
Current Master branch returns the frame caught right before pause

When we call RecordingManager::TakeSnapshot()
ScreenCaptureManager::CopyCurrentFrame() copies from m_FrameCopy 
So I think m_FrameCopy should be updated in ScreenCaptureManager::AcquireNextFrame()
but this method is not called when m_IsPaused==true

thanks

**Comment by sskodje** [comment]
Fixed with ed7ac59
