### ISSUE TITLE
couldn't move my mouse(hangs) immediately after run for few seconds !

### ISSUE THREAD

**Issue by SaddamBInSyed** [sskodje/ScreenRecorderLib#31]
Thanks for the great lib.

I am using this lib from my console exe which is called form window service.
service -> console -> screenLib.

now everything ok except when I starting the service then i can't move my mouse for few seconds (10 - 15  secs) after that all normal. 
it is happening every time recording the screen.

please advise.

Win 10 OS.

thanks.

**Comment by sskodje** [comment]
That's weird. Please try with both hardware encoding off and on, and with "detect mouse clicks" off, and tell me if the problem goes away.

**Comment by SaddamBInSyed** [comment]
I  have tested with advised configuration but NO LUCK. still couldn't able to move my mouse.

 I have downgraded to version to 1.1.7 and now there is no "MOUSE HANG."

but when recording is failing with error "The parameter is incorrect."

please advise.

**Comment by SaddamBInSyed** [comment]
Now working fine recording except for the audio.

**Comment by sskodje** [comment]
Good to hear. For audio, make sure you default audio device is 16bit 44100hz or 16 bit 48000hz, as the other formats are not supported.

**Comment by SaddamBInSyed** [comment]
Audio will work with Version 1.1.7? tried here above config but NO LUCK.

 Bitrate = AudioBitrate.bitrate_128kbps,
 Channels = AudioChannels.Stereo,

**Comment by sskodje** [comment]
Fixed with 9928884caa71bc3be3441fd4ccb6323e434eb950

**Comment by SaddamBInSyed** [comment]
@sskodje 
HI

I will test the mouse lag issue and update you.

by the way, 
Audio is not working still in the latest release. 
tested with win10 pc.
if this is known issue please ignore it.

**Comment by sskodje** [comment]
It's unfortunately hard to know why audio isn't working for you, as everyone has different hardware and software combinations that can produce issues. I can't reproduce the issue on my machines, so unless you can debug it yourself and see if you get any errors, it's not much i can do. 

As i stated earlier, remember the audio output must be 16 bit at 44100 or 48000khz in Windows for audio capture to work.

**Comment by SaddamBInSyed** [comment]
@sskodje 

Hi,  I have tested the same and now no more mouse hangs.

thanks.

meanwhile. one more problem,  I am facing now.

I am starting my screen recording after 1 minute my desktop went to ScreenSaver mode and my PC was locked. 

when I log in again and stop my Screen Recording then most of the time my recorded file is getting corrupted. (sometimes not corrupted)
 
I know in Screensaver mode we can't able to capture SCreen BUt I need the already captured file without corruption.


I am getting OnRecordingFailed() Event with no Error message.

Please advise,

Thanks

**Comment by sskodje** [comment]
I have reproduced the issue. I'll get back to you when i have a fix.

**Comment by SaddamBInSyed** [comment]
I am recording the screen based on the pc lock and unlock event. ( Window service will launch one C# Winform app called ScreenRecorder.Exe)

So when screen saver activates I will not get lock event after some time when I move my mouse it will prompt for unlock screen after unlock I am stopping the recorder and now the file get currupted.

So Is there any configuration something to save a file without curruption?

Since my project mostly rely on your library, now I am STRUGGLING due to file curruption problem.

Also after rec.stop() code line,

Do I need to wait for Completed event even though if  get Error_Failed event.?

Help highly appreciated.

Thanks.

**Comment by SaddamBInSyed** [comment]
@sskodje 

I am waiting here,

Highly appreciate your response regarding the above case.

**Comment by sskodje** [comment]
Either you get a RecordingComplete event, or RecordingFailed event, never both. Do you get the same error if you launch your ScreenRecorder.exe directly, and not from service?

**Comment by SaddamBInSyed** [comment]
"Do you get the same error if you launch your ScreenRecorder.exe directly,"
Yes, I tried with provided TestConsoleApp.exe ; sometimes it gets corrupting the recorded video file.


--
"Enabling "MP4 fast start" will write the video headers at the start of the file, so it should still work up to the point it is corrupted."

--> I will set "IsMp4FastStartEnabled= TRUE" and let you know the results.

Thanks for your response.

**Comment by SaddamBInSyed** [comment]
"Enabling "MP4 fast start" will write the video headers at the start of the file, so it should still work up to the point it is corrupted."
------

As advised above, I have set IsMp4FastStartEnabled= True; 

But No lock. still  I can't play the whole file. ( tried with chrome, VLC player).

Is there any way to solve the **file corruption problem**?

please advise me if there is any more configuration need to change/add.

thanks

**Comment by SaddamBInSyed** [comment]
@sskodje 
Highly appreciate your response regarding the above case.

**Comment by sskodje** [comment]
Well, something obviously crashes on your end, leading to the movie encoder not completing. There is no recovering from that, apart from figuring out what crashes. I can't reproduce the issue, but i have found a flaw that could possible be related while investigating. I'll upload a fix later today. You can also debug the source yourself and see if you can get windows to spit out some better error codes.

Please bear in mind this is a library i made and open sourced on my spare time. I'm not obliged to give any support, nor respond to issues in any timeframe but my own. This is not my job. There is no point repeatedly pinging me in tickets, you won't get any faster response.

**Comment by SaddamBInSyed** [comment]
Well noted.

**Comment by SaddamBInSyed** [comment]
Thanks for the support so far.
