### ISSUE TITLE
HardwareEncodingEnabled -> no Effect

### ISSUE THREAD

**Issue by hth26** [sskodje/ScreenRecorderLib#312]
Regardless of whether 'IsHardwareEncodingEnabled' is true/false, the frame rate is only just above 20fps [with 60fps set]
tested under Windows 11 with:

Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz 2.30 GHz
AMD RYTEN 3-5425U

Helmar Thiere

**Comment by sskodje** [comment]
Both CPUs should support hardware encoding, which should record smooth at 60fps. I have tested 60fps at 1080p to work with hardware encoding on an Intel 8250U machine. CPU encoding on this machine can only do around 25-30fps with low load. It sounds weird if hardware encoding should be non-functional on both your machines. 

Are you sure Windows is actually rendering in 60fps? Playing a 60fps youtube video for example is a good test.
