### ISSUE TITLE
How to get a preview of the current source

### ISSUE THREAD

**Issue by SanicBTW** [sskodje/ScreenRecorderLib#316]
I'm currently trying out the library and I'm wondering if you can make it show a preview of what's happening in the recorder, I have only 2 ideas of how it would work but I don't know if IT could be good or not;
1. Passing a stream that I can use to convert to bitmaps then show that bitmap on the application
2. Having a recorder that doesn't save a file but instead pumps frames to a stream for usage

I really don't know if it could be possible but it would be a neat feature to select a preview of a source and display it, fancy for cool recorders using this lib

**Comment by sskodje** [comment]
Hi! I agree that it's lacking, but i'm working on a feature branch where you can add callbacks to get bitmaps. I'll push it public when i get it to a working state.

**Comment by sskodje** [comment]
This is now added with release 6.3.0

**Comment by SanicBTW** [comment]
Tysm!!
