### ISSUE TITLE
Deadlock on Stop while using version 5.4.0

### ISSUE THREAD

**Issue by alexgoaga** [sskodje/ScreenRecorderLib#318]
Hi,

I am using ScreenRecorder in a project and after few starts and stops, the thread that calls Stop on ScreenRecorderLib gets stuck. I have noticed this behaviour in a few memory dumps analysed.
I have tried to lock access to ScreenRecorderLib object to prevent situations where Stop might be called at the same time with a Start, but even after this I get the same problem.

Are you aware of such an issue? Is it fixed in the latest version 6.2.0?

Thanks,
Alex.

**Comment by sskodje** [comment]
Hi! This sounds like an issue with Media Foundation or the encoders. I'm not able to reproduce it on my test systems unfortunately. I have attached a stress test i use to test stability. You can use it to provoke errors using different configs and encoders. As a baseline, it should be able to run thousands of sequential recordings without issue.

[ScreenRecorderLib stress test.zip](https://github.com/user-attachments/files/17067193/ScreenRecorderLib.stress.test.zip)
