### ISSUE TITLE
How to use h265?

### ISSUE THREAD

**Issue by msalai** [sskodje/ScreenRecorderLib#32]
How can I change this code to use H265 transform instead of H264? This is what I tried:

In **MainWindow.xaml.cs** I changed:

**public H264Profile CurrentH264Profile { get; set; } = H264Profile.Main;** 
from value 77 (**Main**) to value 1 (**eAVEncH265VProfile_Main_420_8**)

In **internal_recorder.cpp** I changed:
	**RETURN_ON_BAD_HR(pVideoMediaTypeOut->SetUINT32(MF_MT_MPEG2_PROFILE, m_H264Profile));**
to
	**RETURN_ON_BAD_HR(pVideoMediaTypeOut->SetUINT32(MF_MT_VIDEO_PROFILE, eAVEncH265VProfile_Main_420_8));**

and in **internal_recorder.h** I changed:
	**const GUID   VIDEO_ENCODING_FORMAT = MFVideoFormat_H264;**
to
	**const GUID   VIDEO_ENCODING_FORMAT = MFVideoFormat_HEVC;**

and I still get message: **The data specified for media type in invalid, inconsistent or not supported by this object.**

**Comment by sskodje** [comment]
I don't know, i have never tried. As far as i know, It's proprietatary so you need hardware support for encoding it, or you need to [buy the codec](https://www.microsoft.com/en-us/p/hevc-video-extensions/9nmzlz57r3t7?activetab=pivot%3Aoverviewtab) for a dollar.
