### ISSUE TITLE
Unspecified error 

### ISSUE THREAD

**Issue by Martin-Pucalka** [sskodje/ScreenRecorderLib#320]
Hi,

Some users of my app are still encountering an 'Unspecified error' exception during recording. I'm running v6.0.0, but I believe there were no changes related to this issue in versions 6.1.0 and 6.2.0.

I've reviewed the related issues:

https://github.com/sskodje/ScreenRecorderLib/issues/204
https://github.com/sskodje/ScreenRecorderLib/issues/176
https://github.com/sskodje/ScreenRecorderLib/issues/119

None of them solved the problem. Here's what I've tried so far:
- The C++ runtime is automatically installed during my app's installation via the MS Store.
- Disabling hardware encoding.
- I've tested both Recorder APIs: WindowsGraphicsCapture and DesktopDuplication.
- Ensuring that the app/recording process runs only once at a time.
- Regarding Windows N: It can't be easily detected. As far as I know, the best approach is to simply attempt recording, and if it fails, show the user a message about downloading the Media Pack or reinstalling the app (as mentioned here: https://devblogs.microsoft.com/oldnewthing/20221229-00/?p=107623). I handle this in a similar way, but I don't think the missing Media Pack is the cause of this issue because:
1) The recording usually doesn't fail immediately; it fails when users stop the recording, and it's being saved.
2) Statistically, I don't think there's a high percentage of users on Windows N.

Could you please offer any advice?

**Comment by sskodje** [comment]
It's not a dependency issue, these are most likely encoder errors. It's endlessly frustrating, but different versions of Windows and machines with different hardware will have different encoders, which sometimes bugs out. Windows Update is a major culprit. I have many times debugged encoder errors and found out Windows was installing an update in the background, messing up the encoders in the process. As for failing when stopping, enabling Fragmented Mp4 in options will ensure the video is still playable if the encoder crashed while finalizing.

I know it's not the answer you want, but i can't really do anything about it apart from rewriting the whole thing to use proper, bug free encoders like FFMpeg. Making sure the computer is updated with windows update and graphics drivers should keep the amount of bugs low.

**Comment by Martin-Pucalka** [comment]
Thank you for the response and for explaining the issue. It's the answer I wanted, and now I understand it better. As you said, there's probably nothing we can do, and FFMpeg can always be used as a more robust alternative. Generally, it's not such a big problem since less than 1% of users experience these errors. However, with 13k MAU, it still leads to many support tickets and bad reviews. Anyway, it's a free app, so they have to tolerate these bugs—at least until I eventually rewrite it using FFMpeg.
