### ISSUE TITLE
video get cropped when starting the application/window recording 

### ISSUE THREAD

**Issue by saman1832** [sskodje/ScreenRecorderLib#327]
bring the application in edge/corner of monitor, now maximized the application and start the recording then clcik on restoe window , now application will come to place near edge now again click on maximized and stop the recording.

See the recording the video will be cropped.

https://github.com/user-attachments/assets/c05e466a-85c8-4c4c-b69c-e50eafb8ba22

**Comment by saman1832** [comment]
@sskodje do you get a chance to have a look on this?

**Comment by sskodje** [comment]
Hi, sorry for the late reply. I'm able to reproduce the issue if the window spans two monitors. I'll investigate more.

**Comment by saman1832** [comment]
yes, for windows having multiple monitors

**Comment by sskodje** [comment]
After some investigation it seems unfortunately this issue is out of my control. The operating system will stop rendering windows, or parts of windows that are outside the monitor bounds.

**Comment by aqibbanday** [comment]
Is it possible this issue is because the when window is moved to the other monitor it is rendered using its GPU and not the other GPu

**Comment by sskodje** [comment]
I don't think so. I can reproduce it on a single gpu. It's just a Windows quirk i guess

**Comment by saman1832** [comment]
@sskodje but this can reproduce on single monitor also see the above video attached that is for single monitor

**Comment by sskodje** [comment]
Yes, i can reproduce it if the window is dragged partially outside the monitor. This is because Windows stops rendering that part of the window.
