### ISSUE TITLE
Not able to record concurrently when using RecorderApi.DesktopDuplication option

### ISSUE THREAD

**Issue by Jason-Tan-ISJ** [sskodje/ScreenRecorderLib#329]
For some reason, I need the recorder to run on window 10 and without the yellow border, there is a use case which require to overlap the recorders to record concurrently.. e.g. recording instance 1 start recording at 00:00:00 for 20 second and recording instance 2 start recording at 00:00:10 for 20 seconds and so on..

By using RecorderApi.WindowsGraphicsCapture, source.IsBorderRequired = False option in window 11, it works perfectly, however, running on window 10, the yellow border will still shows.

When i change to use RecorderApi.DesktopDuplication, the 1st recording has no problem where the subsequent recorder will not be recording, it just create a 0 byte file, I've tested with the sample application(TestConsoleAppDotNetCore.csproj), I'm able to simulate the problem, below is the output, the 2nd recorder seems skipped.

Press ENTER to start recording or ESC to exit
Starting recording
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\0.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\2.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\4.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\6.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\8.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\10.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\12.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\14.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\16.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\18.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\20.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\22.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\24.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\26.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\28.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\30.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\32.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\34.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\36.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\38.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\40.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\42.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\44.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\46.mp4
Recording complete: C:\Users\AppData\Local\Temp\ScreenRecorder\2024-11-22 11-25-04\48.mp4
Press any key to exit

is there any configuration which i need to set or any solution? thanks for helping, log as below.

[Log.txt](https://github.com/user-attachments/files/17866856/Log.txt)

**Comment by sskodje** [comment]
It's unfortunately a limitation of Desktop Duplication, you can only run one instance on it per monitor. Disabling the yellow border is only supported on Windows 11 as you discovered.

A workaround could be to simply crop out the yellow border. For example on a 1080p monitor,if you set the SourceRect on your recording source to [2,2, 1918,1078], it should crop away 2 pixels on all sides.

**Comment by Jason-Tan-ISJ** [comment]
alright.. thanks for the update and idea, appreciated it.
