### ISSUE TITLE
Screen recording produces a lot of lag

### ISSUE THREAD

**Issue by AlexSala07** [sskodje/ScreenRecorderLib#33]
I am trying to record some tests in case they failed. The recording works fine as long as the mouse is not moved. If the mouse is moved, then a lot of lag is produced and everything gets very slow.
I have tried enabling/disabling the hardware encoding, the mouse pointer and mouse clicked variables as well as the quality, the bitrate, etc.

Do know why this happens or what the cause could be?

**Comment by sskodje** [comment]
Hello!

Default, only frames where the screen changes is recorded. When the mouse moves, the screen changes at your monitors refresh rate.  My guess is your system do not support hardware encoding, and/or the framerate is too high for your system. Try using fixed framerate at a reasonable low framerate like 10 fps and see if it fixes it.

**Comment by AlexSala07** [comment]
My monitor should support up to 60 fps and my processor also supports hardware encoding. I tried dropping the frame rate and setting the IsFixedFrameRate to false but none did work.

**Comment by sskodje** [comment]
Thats weird.  I'm on vacation atm, so unfortunately i cant assist you any further.

**Comment by AlexSala07** [comment]
Sure, I will comment if there are any updates.

**Comment by AlexSala07** [comment]
I just tried it on the version 1.1.7 as mentioned in #31 and there is no lag. It works fine.
There may be something with the newer versions.

**Comment by sskodje** [comment]
Is the lag present in newer versions than 1.1.7 apart from the latest v ersion, i.e. does 1.1.12 lag for you?

**Comment by AlexSala07** [comment]
At the moment I'm on vacation but I will inform you on Tuesday.

**Comment by sskodje** [comment]
I believe i have identified and fixed the issue, with 689fe4a555de2c6ed90983ba08df9aa1db9aefd1. I have update to version 1.2.0 on NuGet with some other changes and upgrades. I'll leave this open until you can confirm it works.

**Comment by AlexSala07** [comment]
The version 1.2.0 fixes the problem and works perfectly!
Thank you.
