### ISSUE TITLE
Error: The specified device interface or feature level is not supported on this system.

### ISSUE THREAD

**Issue by btastic** [sskodje/ScreenRecorderLib#34]
Hello,

my recorder options are
```csharp
public static RecorderOptions Options = new RecorderOptions
{
    RecorderMode = RecorderMode.Video,
    //If throttling is disabled, out of memory exceptions may eventually crash the program,
    //depending on encoder settings and system specifications.
    IsThrottlingDisabled = false,
    //Hardware encoding is enabled by default.
    IsHardwareEncodingEnabled = false,
    //Low latency mode provides faster encoding, but can reduce quality.
    IsLowLatencyEnabled = false,
    //Fast start writes the mp4 header at the beginning of the file, to facilitate streaming.
    IsMp4FastStartEnabled = false,

    AudioOptions = new AudioOptions
    {
        Bitrate = AudioBitrate.bitrate_128kbps,
        Channels = AudioChannels.Stereo,
        IsAudioEnabled = false
    },
    VideoOptions = new VideoOptions
    {
        BitrateMode = BitrateControlMode.UnconstrainedVBR,
        Bitrate = 8000 * 1000,
        Framerate = 60,
        IsFixedFramerate = true,
        EncoderProfile = H264Profile.Baseline
    },
    MouseOptions = new MouseOptions
    {
        //Displays a colored dot under the mouse cursor when the left mouse button is pressed.	
        IsMouseClicksDetected = true,
        MouseClickDetectionColor = "#FFFF00",
        MouseClickDetectionRadius = 30,
        MouseClickDetectionDuration = 100,
        IsMousePointerEnabled = true,
    }
};
```

Calling:
```csharp
_recorder = Recorder.CreateRecorder(ScreenRecorderSettings.Options);
_recorder.OnRecordingComplete += Rec_OnRecordingComplete;
_recorder.OnRecordingFailed += Rec_OnRecordingFailed;
_recorder.OnStatusChanged += Rec_OnStatusChanged;

_recorder.Record($@"C:\temp\{Guid.NewGuid()}.mp4");
```

Leads to an event in Rec_OnRecordingFailed where RecordingFailedEventArgs has the message `The specified device interface or feature level is not supported on this system.`

![image](https://user-images.githubusercontent.com/6894999/63947180-bef21a80-ca76-11e9-97bb-30340cdc89ff.png)

DxDiag:
![image](https://user-images.githubusercontent.com/6894999/63947273-e812ab00-ca76-11e9-865e-022c1a5a8ab1.png)

DxDiag Display Feature Levels (Intel Graphics Card)
![image](https://user-images.githubusercontent.com/6894999/63947368-11333b80-ca77-11e9-85f5-b00b6ff12945.png)

DxDiag Display Feature Levels (Dedicated AMD FirePro)
![image](https://user-images.githubusercontent.com/6894999/63947414-260fcf00-ca77-11e9-8bbb-753a9c000155.png)

Please let me know if you need anything else..

**Comment by btastic** [comment]
Disabling the integrated Intel Graphics seems to help. Is it not possible to use integrated graphics for this library?

**Comment by btastic** [comment]
Disabling the fire pro (dedicated graphics) also helped..

**Comment by sskodje** [comment]
I believe what you have is [the same as this issue](https://stackoverflow.com/questions/37349427/desktop-duplication-api-switchable-graphics)

In essence, on computers with switchable graphics (two or more GPU's that can route their output to the same port), Desktop Duplication does not work when you use the dedicated graphics card. A possible workaround is to [force the application to use integrated graphics](https://www.howtogeek.com/351522/how-to-choose-which-gpu-a-game-uses-on-windows-10/)

**Comment by btastic** [comment]
Forcing the application to use integrated graphics works for me. Thank you!

**Comment by sskodje** [comment]
It's only for desktop duplication as far as i know.
