### ISSUE TITLE
No Audio recording working in Testapp

### ISSUE THREAD

**Issue by MerlinCooper** [sskodje/ScreenRecorderLib#38]
Seems that audio is not recorded at all no matter what Audio device I do select in the dropbox. 

"Audio Out" and "Record audio" checkbox are ticked.

**Comment by MerlinCooper** [comment]
Did some more testing. Issue seems to be device specific. Was able to record Audio when selecting "Realtek Digital Output.." as source. Does not work when I do change to my Corsair headset. 

Both devices are shown without issues and are WHQL compatible when running DXDiag? Any advise highly appreciated. 

[ScreenRecorder.zip](https://github.com/sskodje/ScreenRecorderLib/files/3907058/ScreenRecorder.zip)
![DirectXDiag_Corsair Headset](https://user-images.githubusercontent.com/3088879/69899929-549a9000-136d-11ea-8a8b-8f736bc1498e.PNG)
![DirectXDiag_Realtek_Audio](https://user-images.githubusercontent.com/3088879/69899931-56fcea00-136d-11ea-9902-c3141ff186a2.PNG)

**Comment by FoxPride** [comment]
Hi, @MerlinCooper ! Do you have 2 audio devices named "Corsair Vengeance 2000 Headset"? And second question is it bluetooth headset?

**Comment by MerlinCooper** [comment]
@FoxPride. The device is the only one with this name - device is a Bluetooth headset. But does that matter? OBS does not have an issue at all. 

Furthermore I do have other sound devices (e.g. Oculus Rift) where it'a not working as well.

What I figuered out meanwhile is that the maximum Bitrate of the devices not working is 44/48kbit.

**Comment by sskodje** [comment]
I'll do some testing with various devices and see what i figure out. Thanks for reporting the issue.

**Comment by FoxPride** [comment]
About bluetooth devices: I found case when number of channels differs from 2 led to audio distortion.
About same names: audio part of library works with names of devices not ids. So in case when I have 2 audio devices with same name (e.g. microphone and headset) library will pick up first found. 
I'll provide fixes a bit later.
