### ISSUE TITLE
MouseClicks Not Showing when going through User32.dll

### ISSUE THREAD

**Issue by MJWherry** [sskodje/ScreenRecorderLib#39]
Mouse click recording works fine when i use my mouse, but simulating mouse clicks by going through SendInput(...) does not show. Below is the method called

`[DllImport("user32.dll", EntryPoint = "SendInput")]`
`private static extern uint _sendInput(uint nInputs, [MarshalAs(UnmanagedType.LPArray), In] InputStruct[] pInputs, int cbSize);`

**Comment by sskodje** [comment]
Fixed with 4d0d60bed38db3197ccb6f3819eaca44de9b67c8
