### ISSUE TITLE
How to record video to a stream?

### ISSUE THREAD

**Issue by AndreasSchmid1** [sskodje/ScreenRecorderLib#4]
Hello sskodje. Thank you for this amazing library. Is it possible to record the video to a stream? 
This would make the use more flexible. Thank you for help in advance

**Comment by sskodje** [comment]
Hello! 

It definitely is possible! I will add this request, and have a look soon. I have thought of this myself, as it would indeed be very flexible.

**Comment by AndreasSchmid1** [comment]
any news on this feature? really looking forward to it

**Comment by sskodje** [comment]
I've  been a bit busy, so unfortunately not much. I'll try get some work done on it this week.

**Comment by sskodje** [comment]
Implemented with commit bee13d32a23cf0fbf750311952d9d6c5ee2f5f3b. You can record to either a System.IO.Stream, or make your own implementation of IStream.

**Comment by smedasn** [comment]
The streaming feature looks great. I try make it work with web api controller and use pushcontentstream to stream the content to localhost. I was thinking about using a MemoryStream, but i guess it is a bad idea because it will likely fill up the RAM constantly. Does anyone have any idea how to get such a system up and running?

**Comment by sskodje** [comment]
> 
> 
> The streaming feature looks great. I try make it work with web api controller and use pushcontentstream to stream the content to localhost. I was thinking about using a MemoryStream, but i guess it is a bad idea because it will likely fill up the RAM constantly. Does anyone have any idea how to get such a system up and running?

A naive way could be to just plug in the output stream directly, but i haven't tested. 

      new PushStreamContent((outputStream, httpContent, transportContext) =>
            {
             //outputStream can probably be used as stream to record to.
            }

**Comment by tvfire** [comment]
I also tried to stream the "stream" via http. Unfortunately without success. @smedasn did you manage that somehow?

**Comment by smedasn** [comment]
Unfortunately no. I tried to adapt working examples with FileStream but i was not successful. I think it does not work because the stream from the lib does not have a length, but it is an assumption.
I guess the only one here capable of solving this issue is sskodje :)

**Comment by sskodje** [comment]
The issue is twofold. First you need to create a custom stream wrapper to support streaming without a length. The default implementation is very naive in this regard. I can try help you a simple implementation of such a stream here. I believe this is the simplest implementation that can work.


    public class CustomStream : Stream
     {
        private Stream _writeStream;
        public CustomStream(Stream writeStream)
        {
            _writeStream = writeStream;
        }


        public override bool CanRead => _writeStream.CanRead;
         //Tell it to always return true on CanSeek, iven if you can't.
        public override bool CanSeek => true;

        public override bool CanWrite => _writeStream.CanWrite;

        public override long Length
        {
            get
            {
                return 0;//Just tell it to return 0 for endless.
            }
        }

        public override long Position { get => _writeStream.Position; set => _writeStream.Position = value; }

        public override void Flush()
        {
            _writeStream.Flush();
        }

        public override int Read(byte[] buffer, int offset, int count)
        {
            return _writeStream.Read(buffer, offset, count);
        }

        public override long Seek(long offset, SeekOrigin origin)
        {
            //This is called before every write, so return the offset to write to.
            return offset;
        }

        public override void SetLength(long value)
        {
            //this won't work.
        }

        public override void Write(byte[] buffer, int offset, int count)
        {
            _writeStream.Write(buffer, offset, count);
            _writeStream.Flush();
        }
    }


The second issue is that the video must be encoded "fragmented", which means that it can be played without an end. This was missing from the library, but i added it with 20211ca60b1059c818f48cebe8ad8d84cafd58fd .

**Comment by smedasn** [comment]
Thank you so much for your amazing support. I will test it as soon as I have time.
