### ISSUE TITLE
Is it available for 4.5?

### ISSUE THREAD

**Issue by qayyumabro** [sskodje/ScreenRecorderLib#40]
Can you please point me to a compiled version of the lib that is based on .net 4.5 version?

**Comment by sskodje** [comment]
You can just download the source, change the <TargetFrameworkVersion> in the .vxproject file to 4.5 and compile it.  But may i ask why you don't simply increase your .net target version for your .net project? This library won't work on Windows Vista  anyway.

**Comment by qayyumabro** [comment]
Thanks so much for the quick reply. Will this still work win7 and onward. I don't know about Microsoft Media Foundation.

**Comment by sskodje** [comment]
No, i'm sorry, this library requires Windows 8 or higher.

**Comment by qayyumabro** [comment]
No problem at all, it looks great lib anyway.
