### ISSUE TITLE
No screen recording for Portrait monitors

### ISSUE THREAD

**Issue by lupusilviu** [sskodje/ScreenRecorderLib#43]
Hello,

It seems that the application does not record any images from a monitor that is Portrait. It gets the mouse movements, but not the screen images. It works if I set the monitor to Landscape only.

Is there a limitation in this sense, or I am using it wrong? I tested with the TestApp from the repository.

**Comment by sskodje** [comment]
Thanks for reporting the issue. I'll have a look and try to figure out what goes wrong in portrait mode.

**Comment by sskodje** [comment]
I'm working on a fix, shouldn't bee too long.

**Comment by lupusilviu** [comment]
Thank you

**Comment by tweakux** [comment]
Very interested in the portrait limitation as well
I'm using full HD 1080*1920

Thanks.

**Comment by sskodje** [comment]
Fixed with 4d0d60bed38db3197ccb6f3819eaca44de9b67c8

**Comment by lupusilviu** [comment]
Thank you very much for the fast fix. It is working like a charm now.
