### ISSUE TITLE
Hanging

### ISSUE THREAD

**Issue by MJWherry** [sskodje/ScreenRecorderLib#45]
We have the recorder running on it's own thread to record ui automation tests. The issue is that for some reason the recorder is causing a hang. Checking the crash logs, i see these two errors below in window events. This causes the nunit tests to hang until jenkins ends up killing the jobs

`Exception Info: System.NullReferenceException
   at <Module>.ScreenRecorderLib.ManagedIStream.Seek(ScreenRecorderLib.ManagedIStream*, _LARGE_INTEGER, UInt32, _ULARGE_INTEGER*)`

`Exception Info: System.OutOfMemoryException
   at <Module>.ScreenRecorderLib.ManagedIStream.Write(ScreenRecorderLib.ManagedIStream*, Void*, UInt32, UInt32*)`

**Comment by sskodje** [comment]
The stream throws when writing because the process is out of memory. I think the limit for a 32 bit process is 2GB, and 4GB for a 64 bit process. What first comes to mind is that you are recording a lengthy recording to a memory stream, which in that case quickly will fill the process memory.

If that is not the case, it could be a memory leak that is over time filling up the process memory.

**Comment by MJWherry** [comment]
Im recording many (around 100 currently) tests but the recordings only last about 2-10 seconds. also, i have a wrapper class for the lib and i have 1 static mem stream, and recreate when i begin recording, and end recording i decide if i want to write that to a file or not, unsure why im running into a memory issue...it would be okay if it didnt hang but the entire nunit project hangs due to this

**Comment by sskodje** [comment]
That sounds like a memory leak yeah. Perhaps related to the memorystream not being disposed correctly.

**Comment by MJWherry** [comment]
Ended up just recreating the stream & recorder instead of just the stream (there may have been an issue when stopping the recorder and recreating the stream then using the newly recreated sstream with the recorder). Working with fix of recreating the recorder instead of stopping then starting again .
