### ISSUE TITLE
VideoOptions Snapshot format seems to be Slideshow format?

### ISSUE THREAD

**Issue by joreg** [sskodje/ScreenRecorderLib#46]
when setting VideoOptions SnapshotFormat this actually sets the Slideshow format?!

Snapshot mode records just a single frame to the mp4, right?

**Comment by sskodje** [comment]
Snapshot takes a picture of the screen. It could perhaps more aptly have been named screenshot.

Slideshow is a series of snapshots, so at 10 fps it takes 10 snapshots per second in format specified in VideoOptions.SnapshotFormat.
