### ISSUE TITLE
Simply does not work

### ISSUE THREAD

**Issue by denik7770** [sskodje/ScreenRecorderLib#49]
![Screenshot (7)](https://user-images.githubusercontent.com/47399010/75611837-00db4680-5b16-11ea-8dd9-2980b6a9be8e.png)
Does not work at all, nor console, nor desktop...
OS: Win10...

**Comment by sskodje** [comment]
Do you have a Windows 10 version without media features?

https://www.microsoft.com/en-us/software-download/mediafeaturepack

**Comment by FoxPride** [comment]
Greetings,  sskodje!
I have user with the same error on Windows 10 Home. After some research I found this [link1](https://stackoverflow.com/questions/48930499/how-do-i-encode-raw-48khz-32bits-pcm-to-flac-using-microsoft-media-foundation) [link2](https://stackoverflow.com/questions/48930499/how-do-i-encode-raw-48khz-32bits-pcm-to-flac-using-microsoft-media-foundation)
