### ISSUE TITLE
Is it possible to record a lossless h264 mp4 file?

### ISSUE THREAD

**Issue by smedasn** [sskodje/ScreenRecorderLib#5]
Hello there. Thanks for the great library sskodje!
I am wondering if it is possible to record a lossless h264 mp4 file?

Or alternatively when this is not possible what are the "best quality" settings one can choose?

Thanks in advance

**Comment by sskodje** [comment]
Hello!

Unfortunately the library is currently hardcoded to use the h264 encoder.  I don't think there is a way to encode lossless h264 video. You can modify the hardcoded values [here](https://github.com/sskodje/ScreenRecorderLib/blob/94acffc2676ef60bde6686f2657e706a02e7c51c/ScreenRecorderLib/internal_recorder.cpp#L107) to change the encoder. You can find documentation on the available codecs [here](https://msdn.microsoft.com/en-us/library/windows/desktop/ff819077(v=vs.85).aspx). Ideally in the future there will be a method to query the system for available codecs and configure it. 

For now, you can only adjust the video bitrate. Obviously the higher, the better quality.

**Comment by sskodje** [comment]
Ive just pushed an update that lets you configure the H.264 [encoder profile](https://en.wikipedia.org/wiki/H.264/MPEG-4_AVC#Profiles) to Main or High. Setting it to Higher profile will give better quality per bitrate, while being more resource intensive both at decoding and encoding, and a reduction in device compatibility.

**Comment by smedasn** [comment]
Thank you so much sskodje
