### ISSUE TITLE
Proper recording of still images

### ISSUE THREAD

**Issue by hakito** [sskodje/ScreenRecorderLib#53]
When recording a display where no pixels change the final recording has only a fraction of the real length and no audio is recorded at all.

MediaInfo
```
Duration                                 : 100 ms
```

TestApp
```
Elapsed: 2s:425ms
```

I think the recorder should not send the frame directly to the writer when captured. Instead it should keep the frame until the next frame is recorded or the loop is paused / stopped. The frame duration is then delayed calculated when the next frame appears (or recording is paused / stopped).

**Comment by sskodje** [comment]
Fixed with f577fd5f5a5bf16967d983d8e7b13467ccba42c1
