### ISSUE TITLE
Independent recording of audio stream

### ISSUE THREAD

**Issue by hakito** [sskodje/ScreenRecorderLib#54]
Regarding PR #52 and f577fd5f5a5bf16967d983d8e7b13467ccba42c1

I could not easily rewrite the code to push the audio frames independently because:

- When starting a recording with silence the loopback_capture does not receive a packet until some audio is sent to the input device. (for example: recording output device and starting a playback a few seconds after recording)
- Simply setting the starttime does not work, because the MPEG4 sink ignores the starttime values of samples. (It has the [MEDIASINK_RATELESS](https://docs.microsoft.com/en-us/windows/win32/api/mfidl/nf-mfidl-imfmediasink-getcharacteristics) flag)
- The current [workaround was to insert silence manually](https://github.com/sskodje/ScreenRecorderLib/blob/872f9a0e7759f3931bb9df4051a9e01bde20d0c6/ScreenRecorderLib/internal_recorder.cpp#L1368). I think a better method would be to use 
```c++
if (model.Audio.size() > 0) {
	hr = WriteAudioSamplesToVideo(model.StartPos, model.Duration, m_AudioStreamIndex, model.Audio);
	if (FAILED(hr)) {
		_com_error err(hr);
	}
}
else
	m_SinkWriter->SendStreamTick(m_AudioStreamIndex, model.Duration);
```
I tried this and this works great (for silenc at the beginning). 
- But afterwards even when the output device does no playback the captureClient continues to receive packets. So audio size is not 0 anymore. So for more accurate audio timings I think it would be useful to consider [```pu64DevicePosition``` from ```IAudioCaptureClient::GetBuffer```](https://docs.microsoft.com/en-us/windows/win32/api/audioclient/nf-audioclient-iaudiocaptureclient-getbuffer?redirectedfrom=MSDN).

Probably an even better way handle the audio is to use a MediaSource? Multiple audio inputs could be simply combined using [```MFCreateAggregateSource```](https://docs.microsoft.com/en-us/windows/win32/api/mfidl/nf-mfidl-mfcreateaggregatesource?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(MFIDL%2FMFCreateAggregateSource)%3Bk(MFCreateAggregateSource)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.5.2)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.5.2)%3Bk(DevLang-C%2B%2B)%3Bk(TargetOS-Windows)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.5.2)%26rd%3Dtrue).

I pushed my experimental changes to https://github.com/hakito/ScreenRecorderLib/tree/independent_audio

**Comment by sskodje** [comment]
It's probably possible, but i'm not sure how to create a IMFMediaSource that delivers [wasapi loopback capture](https://docs.microsoft.com/en-us/windows/win32/coreaudio/loopback-recording). The SendStreamTick is interesting.

**Comment by sskodje** [comment]
I can't get the streamtick to work properly. It leads to glitches in the audio, or just chokes the encoder completely. I think thats why i used the zero padding to begin with..
