### ISSUE TITLE
Suggestion - Replay buffer

### ISSUE THREAD

**Issue by Syrou** [sskodje/ScreenRecorderLib#59]
A nice feature to the library would be the ability to capture the latest 1 min which just keeps on recording the latest 1 min until you stop!

**Comment by sskodje** [comment]
I think such a feature should be implemented in the application using the library. I do not think it's a possibility of MF video encoder to overwrite the current stream being recorded to.

The easiest solution for you is probably just to run a loop with two or more rotating files that records one minute, then starts a new recording and discarding the previous file when the next completes.
