### ISSUE TITLE
Quality settings not working as expected

### ISSUE THREAD

**Issue by stanecli** [sskodje/ScreenRecorderLib#60]
Hi,
I want to use the library for recording automated tests.
When I run it on two identical computers, with the same settings, I get different results.
To be specific, the quality and file size changes, and some of the settings work on one machine, some work on the other.
These are the options I use on every machine:
```
RecorderMode = RecorderMode.Video,
IsThrottlingDisabled = false,
IsHardwareEncodingEnabled = true,
IsLowLatencyEnabled = true,
IsMp4FastStartEnabled = false,
VideoOptions = new VideoOptions
{
    BitrateMode = BitrateControlMode.UnconstrainedVBR,
    Framerate = 30,
    Bitrate = 500 * 1000,
    IsFixedFramerate = false,
    EncoderProfile = H264Profile.Baseline
},
DisplayOptions = new DisplayOptions
{
    Top = 0,
    Left = 0,
    Bottom = 768,
    Right = 1024,
    MonitorDeviceName = System.Windows.Forms.Screen.PrimaryScreen.DeviceName
},
AudioOptions = new AudioOptions
{
    IsAudioEnabled = false
}
```
On one machine, I can achieve a 2Mb size for a 1 minute video, with Quality mode, and quality set to 30%.
On the other machine, none of those settings do anything, the video is 150Mb perfect quality every time.
When I set UnconstrainedVBR and set the bitrate to match the quality roughly as in quality mode, it works on the second machine, but now the first produces a 150Mb video.
Could you help me figure out what's going on? This drives me crazy.
Thanks!

**Comment by sskodje** [comment]
Hello!

I can understand the frustration. My guess is it's the hardware encoder that is not doing what it should. Every graphics chip producer makes their own hardware video encoders.

First off, i would update graphics drivers on both machines to the newst version. If that does not fix it, is the graphics hardware different on the two machines? Does it work if you encode in software mode?

**Comment by stanecli** [comment]
Thanks for the suggestions! I will try them out and update my findings.

**Comment by stanecli** [comment]
Updating the drivers did the trick, software encoding didn't seem to affect anything for me. But for now at least it's consistent on all machines. Thanks!
