### ISSUE TITLE
Catastrophic Failure

### ISSUE THREAD

**Issue by colinpayette** [sskodje/ScreenRecorderLib#61]
No matter what I try I get "Catastrophic Failure". It recorded once and does this ever since. I've tried rebooting, rebuilding, etc. This error message is not very informative, nor can I find it anywhere in the source to debug it.

I have deleted temp files. I have tried recording to a stream, etc.

![image](https://user-images.githubusercontent.com/334059/80249498-cc23d100-8626-11ea-9565-00bf65e012e9.png)

**Comment by sskodje** [comment]
You are correct, that's not much to go on. The error is a pretty nondescript E_UNEXPECTED "Catastrophic Failure", which is thrown by one of the Windows API's that is called. It could be a million things, from a windows udates messing it up, video drivers, etc. The easiest way to narrow it down is probably to start a recording with debugging and stepping through the initialization code to see where it errors out.

**Comment by colinpayette** [comment]
Thanks. After updating video card drivers it happens about 50% of the time. Reboots sometimes fix it. I was able to debug it down to InitializeDesktopDupl in internal_recorder.cpp line 1060

`
// Create desktop duplication
hr = pDxgiOutput1->DuplicateOutput(
	pDevice,
	&pDeskDupl);
	RETURN_ON_BAD_HR(hr);
	pDxgiOutput1.Release();
`
That's where the E_UNEXPECTED failure is. It's odd because it's not 100% of the time that it fails. I can't reproduce it on another computer. I'm thinking perhaps it's something caused by running this through remote desktop.

**Comment by diegoadan** [comment]
Hi colinpayette, I had a very similar issue when calling to DuplicateOutput() method, and I found the solution here https://support.microsoft.com/nb-no/help/3019314/error-generated-when-desktop-duplication-api-capable-application-is-ru

Hope that helps you,

**Comment by hanhsia** [comment]
I can reproduce the same issue:
1. run the application in a rdp connected host. it works fine
2. run the application and disconnect the rdp and reconnect again.
3. The application can't call pDxgiOutput1->DuplicateOutput successfully any more. I need to remote the remote host.

**Comment by hakito** [comment]
I can confirm this. I also found a discussion on this here: https://learn.microsoft.com/en-us/answers/questions/1068807/desktop-duplication-api-doesnt-work-over-remote-de
