### ISSUE TITLE
Record two screen

### ISSUE THREAD

**Issue by thecco** [sskodje/ScreenRecorderLib#68]
How can I record two monitors at the same time?

In my case,

Primary monitor is on the right, Second monitor is on the left.
So Second's (0,0) coordinate is (-3440,15).
The primary monitor (0,0) is (3400,0).

![dsadasdasd](https://user-images.githubusercontent.com/11549888/83519371-cae39f00-a516-11ea-876f-43517220cf10.PNG)

I want to record the area between the two monitors.
![dsadasdasd - 복사본](https://user-images.githubusercontent.com/11549888/83519423-e5b61380-a516-11ea-98d6-85ff0abbd95f.PNG)

**Comment by sskodje** [comment]
That is unfortunately not possible, due to limitations in the Windows Desktop Duplication API. You can for example try [FFmpeg](https://trac.ffmpeg.org/wiki/Capture/Desktop) instead.

**Comment by 5cutters** [comment]
> That is unfortunately not possible, due to limitations in the Windows Desktop Duplication API. You can for example try [FFmpeg](https://trac.ffmpeg.org/wiki/Capture/Desktop) instead.

Is that also the case using the WindowsGraphicsCapture RecorderApi? (i can't get it to work so i guess so)

**Comment by sskodje** [comment]
This is outdated info now. You can record two or more screens, and crop out the region you want. See https://github.com/sskodje/ScreenRecorderLib/wiki/Quickstart-guide-v5.x.x-and-newer.#source-properties and https://github.com/sskodje/ScreenRecorderLib/wiki/Quickstart-guide-v5.x.x-and-newer.#change-the-options-with-recorderoptions

**Comment by 5cutters** [comment]
Thanks for confirming that. Must be a problem with the my screenrect code somewhere where it's spanning over displays. I'll investigate further.
