### ISSUE TITLE
Unhandled Exception: System.IO.FileLoadException: A procedure imported by 'ScreenRecorderLib.dll' could not be loaded.

### ISSUE THREAD

**Issue by richardli7** [sskodje/ScreenRecorderLib#7]
**Many thanks to the author sskodje for this great tool!**

Currently it runs well on my Windows 10, but when it goes to Windows 7, it popped up such an error:

```
Unhandled Exception: System.IO.FileLoadException: A procedure imported by 'ScreenRecorderLib.dll' could not be loaded.
at CreateRecording(String videoPath)
at AutoTaskMode()
at Program.Main(String[] args)
```

Tried to use Regsvr32 'ScreenRecorderLib.dll' under Administrator mode but nothing changed.
![image](https://user-images.githubusercontent.com/20408106/36877765-b1a85320-1e20-11e8-9d97-0712a90c4cf4.png)

Could anyone help me on this?
Much appreciated.

By the way, I use file size to determine if the video has finished its writing to the hard disk. Hope this tip could help someone else.

**Comment by sskodje** [comment]
Unfortunately, Windows 7 is not supported, because the Desktop Duplication API this library uses was only intruduced in Windows 8.

**Comment by richardli7** [comment]
Thanks, very much appreciated!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
