### ISSUE TITLE
Could you please make a Win32 C++ sample?

### ISSUE THREAD

**Issue by chen2qu** [sskodje/ScreenRecorderLib#71]
This lib worked great when I'm testing it. Thanks for the great work!
One issue for me is that I need to use C++ and all the samples are in C#. And I don't think I'm the only one falls into this situation. So it will be even greater if you can make a Win32 C++ sample too.  
Thanks again!

**Comment by sskodje** [comment]
Since this is a managed library, it will only work in C++/CLI. The current Nuget package unfortunately does not work with C++/CLI, but i'll fix that for the next version and add a small sample project.

**Comment by sskodje** [comment]
Fixed with 3c3b75d4c361309071d179d311b9557d02d4eaef and 48b27ebf6bda825d3cd40fc5baf77811c94548f6
