### ISSUE TITLE
Auto flushing not working?

### ISSUE THREAD

**Issue by xeo545x39** [sskodje/ScreenRecorderLib#72]
I've recorded video successfully, but the stream in not flushing automatically, so when an output is FileStream, then a file has 0 bytes size all the time while recording.

I've used MP4 fragmentation and fast start properties with no effect - still can't play as live stream.
Should I write to a different type of stream to get live stream?

```csharp
public partial class Form1 : Form
{
    private const string fileName = "output.mp4";

    private ScreenRecorderLib.Recorder recorder;
    private Stream outputStream;
    private Stream inputStream;

    public Form1()
    {
        InitializeComponent();

        recorder = Recorder.CreateRecorder(new RecorderOptions
        {
            RecorderMode = RecorderMode.Video,
            IsMp4FastStartEnabled = true,
            IsFragmentedMp4Enabled = true,
            IsThrottlingDisabled = false,
            IsHardwareEncodingEnabled = true,
            IsLowLatencyEnabled = false,
            VideoOptions = new VideoOptions
            {
                BitrateMode = BitrateControlMode.UnconstrainedVBR,
                Bitrate = 8000 * 1000,
                Framerate = 60,
                IsFixedFramerate = true,
                EncoderProfile = H264Profile.High
            }
        }); ;

        recorder.OnStatusChanged += Recorder_OnStatusChanged;
        recorder.OnRecordingComplete += Recorder_OnRecordingComplete;
        recorder.OnRecordingFailed += Recorder_OnRecordingFailed;
    }

    private void Recorder_OnRecordingFailed(object sender, RecordingFailedEventArgs e)
    {
        label1.Invoke(new Action(() =>
            label1.Text = $"Failed - {e.Error}"));

        outputStream?.Dispose();
    }

    private void Recorder_OnRecordingComplete(object sender, RecordingCompleteEventArgs e)
    {
        label1.Invoke(new Action(() =>
            label1.Text = $"Completed"));

        outputStream?.Dispose();
    }

    private void Recorder_OnStatusChanged(object sender, RecordingStatusEventArgs e)
    {
        label1.Invoke(new Action(() =>
            label1.Text = e.Status.ToString()));
    }

    private void button1_Click(object sender, EventArgs e)
    {
        outputStream = new FileStream(fileName, FileMode.Create);

        recorder.Record(fileName);
    }

    private void button2_Click(object sender, EventArgs e)
    {
        recorder.Stop();
    }

    private void button3_Click(object sender, EventArgs e)
    {
        inputStream = new FileStream(fileName, FileMode.Open);

        vlcControl1.SetMedia(inputStream);
        vlcControl1.Play();
        vlcControl1.VlcMediaPlayer.Stopped += VlcMediaPlayer_Stopped;
    }

    private void VlcMediaPlayer_Stopped(object sender, Vlc.DotNet.Core.VlcMediaPlayerStoppedEventArgs e)
    {
        inputStream.Dispose();
        inputStream = null;
    }
}
```

**Comment by sskodje** [comment]
private void button1_Click(object sender, EventArgs e)
    {
        outputStream = new FileStream(fileName, FileMode.Create);

        recorder.Record(fileName);
    }

Here you are opening a filestream, creating a new file with the given path, then you are passing the path to the Recorder instead of the filestream. The Recorder instance is then creating it's own internal filestream and writes to it, instead of your stream.

**Comment by xeo545x39** [comment]
I've tried both ways - my own stream and a path. Both are writing bytes only after stopping recording. As I see AutoFlushing is only in StreamWriter, not FileStream. So should I use Flush manually? In a timer? Sounds not good.

**Comment by sskodje** [comment]
Filstream continually writes to the file, no flushing is needed. You can observe this by starting a recording, and opening the file in Windows with i.e. VLC.

**Comment by xeo545x39** [comment]
Nope. The documentations of `Dispose` and `Flush` methods of `FileStream` say:
`This method disposes the stream, by writing any changes to the backing store and closing the stream to release resources.`
https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.dispose?view=netcore-3.1#System_IO_Stream_Dispose

`Any data previously written to the buffer is copied to the file and the buffer is cleared except for its encoder state.`
https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream.flush?view=netcore-3.1#System_IO_FileStream_Flush

As I said earlier, the output file has 0 bytes size until I stop recording.

**Comment by sskodje** [comment]
This isn't really the place to learn how .net internals work. You can see how it works[ here](https://referencesource.microsoft.com/#mscorlib/system/io/filestream.cs). If there isn't anyhing directly related to this library, i'm going to close this issue.

**Comment by xeo545x39** [comment]
LOL So go and learn or prove that FS writes, because I've tested it many times with `Write` method and it does not write until flushed or disposed manually.
