### ISSUE TITLE
[Feature request] single window recording

### ISSUE THREAD

**Issue by jonathan25** [sskodje/ScreenRecorderLib#73]
Hi,
I like this library and it's working perfectly for what I use it for, given that this supports fragmented MP4 while the current version of ``Windows.Media.Transcoding`` does not. However, Windows added a new API that allows to record single windows by giving a HWND

Here's some info.
https://blogs.windows.com/windowsdeveloper/2019/09/16/new-ways-to-do-screen-capture/
some samples:
UWP: https://github.com/robmikh/SimpleRecorder
Win32 and WPF: https://github.com/Microsoft/Windows.UI.Composition-Win32-Samples/tree/master/dotnet/WPF/ScreenCapture

I know this library is called ``ScreenRecorderLib`` but adding this feature would be nice.

**Comment by sskodje** [comment]
Looks quite practical. I'll have a look at it.

**Comment by luky92** [comment]
Any ETA on this?

**Comment by sskodje** [comment]
Don't hold your breath. It think it requires a substantial rewrite of the code, and i don't have a lot of time for it atm.

**Comment by sskodje** [comment]
Window recordings using Windows Graphics capture is now available from version 3.0.0
