### ISSUE TITLE
Watermark Support

### ISSUE THREAD

**Issue by Willy-Kimura** [sskodje/ScreenRecorderLib#77]
Is there a way to include a watermark or logo when recording videos?

**Comment by sskodje** [comment]
Unfortunately no. I'll put it as an enhancement request.

**Comment by Willy-Kimura** [comment]
Great, thanks. Will look into it.

**Comment by pdesantis** [comment]
This would be super cool!

**Comment by sskodje** [comment]
Added in 83202d6490ba66d1bba21f0f94e9a7e25449dbe8
