### ISSUE TITLE
Exception  Unexpected WaitForMultipleObjects evey time I stopped the recording 

### ISSUE THREAD

**Issue by abramovi** [sskodje/ScreenRecorderLib#8]
HI 

Every time I stop the recording I get the following error:

> Error: Unexpected WaitForMultipleObjects return value 4294967295 on pass 126 after 2011654736 frames

My Recording configuration is:
                       `RecorderOptions options = new RecorderOptions
			{
				RecorderMode = RecorderMode.Video,
				IsThrottlingDisabled = false,
				AudioOptions = new AudioOptions
				{
					Bitrate = AudioBitrate.bitrate_128kbps,
					Channels = AudioChannels.Stereo,
					IsAudioEnabled = true
				},
				VideoOptions = new VideoOptions
				{
					Bitrate = 8000 * 1000,
					Framerate = 60,
					IsMousePointerEnabled = true,
					IsFixedFramerate = true,
					EncoderProfile = H264Profile.Main
				}
			};`

**Comment by sskodje** [comment]
I am aware of that error output, but it should not affect the recording in any way. You can safely ignore it.

**Comment by abramovi** [comment]
it looks like this exception prevent the **OnRecordingComplete** event from being invoked. So there is no way to know when exactly the process completed.

**Comment by sskodje** [comment]
Fixed with commit f87eba4cd3e1571972bfa65d4e6410aef0b3864d
