### ISSUE TITLE
OnRecording Failed : Idxgifactory enumadapters

### ISSUE THREAD

**Issue by SaddamBInSyed** [sskodje/ScreenRecorderLib#80]
Hi @sskodje 

I am recording the screen display every 5 secs (per video record length is 10 min). after some time I am getting the below error and no video was recorded.

**`OnRecording Failed : Idxgifactory enumadapters; there is no adapter with specified ordinal`**

could you please advise for the same.

I am using v1.3.

thanks.

**Comment by sskodje** [comment]
The error message is normal, and happens every run when iterating display adapters. But something goes wrong shortly after getting the display adapter without setting an error code causing GetLastError() to return that one.

If you are not running the lastest version, i'd try that first.
