### ISSUE TITLE
Recording always fails immediately with "Catastrophic failure"

### ISSUE THREAD

**Issue by micahmo** [sskodje/ScreenRecorderLib#81]
Hi sskodje,

I hope you are doing well! We are using your library in our product and are very happy with it! You have helped us with some issues before, and we really appreciate your responsiveness. I'm back with another strange issue. To isolate the issue from anything in our code, I cloned your repository, built, and ran the sample app. The recording always fails immediately with "Catastrophic failure", regardless of the configuration.

I tried to break on all C++, CLR, and Win32 exceptions, but there weren't any. I also do not see any logging in the Output window.

![](https://i.imgur.com/o2wf5Qu.png)

The problem occurs whether I use hardware or software encoding. Another note is that I am trying to perform this action over RDP. I'm not sure if that has any affect, but I believe it has worked in the past. Here are some basic PC stats, if it's helpful.

![](https://user-images.githubusercontent.com/7417301/51540143-b6bc6780-1e23-11e9-99fc-81d737c3cdfe.png)

Let me know if there is any other info I can provide!

**Comment by micahmo** [comment]
Upon further investigation, it looks like the call to DuplicateOutput is failing in dxgi.dll.

![](https://imgur.com/KyTVyZC.png)

**Comment by sskodje** [comment]
Did it just suddenly happen? It's an undocumented error that probably means something undisclosed is interfering with the graphics system. Some culprits i've experienced is Windows Update, if in the middle of an update and pending restart, this could happen. Another is broken video drivers.

**Comment by micahmo** [comment]
Thanks for the response! The issue is intermittent on my system (happened a while ago, then was fine, now just started happening again). It also happens on some other developers' machines.

I checked Windows Update, and it does not look like there is a pending restart. As for graphics drivers, since the session is over RDP, I guess it's using the "Microsoft Remote Display Adapter" virtual graphics card, so it should have built-in drivers.

I don't believe I have an iGPU, although I do have two discrete GPUs. Could that have any effect?

**Comment by micahmo** [comment]
Aha! Although Windows Update did not say that there was a pending restart, I took your advice and restarted anyway. Sure enough, it works just fine now!

At this point, I'm planning to add some error handling to our application so that if we get this error back from your library, we can recommend that the user restart their system.

I'll plan on closing this issue since this is a satisfactory resolution for me. Once again, thanks for your very quick and helpful support!

**Comment by sskodje** [comment]
These Windows quirks really are a pain sometimes. I'm glad you got it sorted out.
