### ISSUE TITLE
Application resolution change once 

### ISSUE THREAD

**Issue by hulaomr** [sskodje/ScreenRecorderLib#85]
Hello,

Perhaps is a stupid question. 

The library is integrated with success in a WinForm application (using Telerik library). 

- In the development workstation the application is working as expected, recording the application screen video. 

- In a tablet device (with Windows 10 Pro), once the record button is click, the application change the resolution and damage the layout indefinitely. Which means, once I open the application again, the layout situation is the same. 

One way to solve this situation was to reset the tablet ("Reset your PC" option, https://support.microsoft.com/en-us/help/12415/windows-10-recovery-options). 

Please, may I know if there are something behind the scenes that could be causing this situation and any suggestion to manage it. Unfortenelly, I cannot upload pictures of the application.

Thanks

**Comment by sskodje** [comment]
I'm not completely understanding what happened. Do you mean the size or location of your winforms application changed, or that the resolution of Windows changed?

**Comment by hulaomr** [comment]
At the moment of reporting the issue, it was not easy to answer your question. 

Just now, I got with the **setting that is changing** once the recorder is enable. It seems the following registry key is added:

Computer\HKEY_USERS\S-1-5-21-3909946418-952361731-3876965913-1001\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\

C:\Users\user\Desktop\remote\Release\app.exe   HIGHDPIAWARE

Once this setting is removed, the application work as expected. 

Another way to change this setting is by the following dialog:

![image](https://user-images.githubusercontent.com/36808114/90986624-8e0ecd80-e584-11ea-8a42-44c0434f38a1.png)

Any idea why this setting is changed?

Thanks

**Comment by sskodje** [comment]
I have no idea. The setting is not changed in this code at least. It is possible that one of the Microsoft API's is doing it in the background for one reason or another, but its not happening to me when i test on a winform app. The DPI aware setting is supposed to be set in the winform applications manifest file. What happens if you explicitely set it to false, like this?

  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">false</dpiAware>
    </windowsSettings>
  </application>

**Comment by hulaomr** [comment]
Thanks for your suggestion. Appreciated.

However, the setting is still set after recording is enabled. I think wherever the manifest file is, the OS override this value. As you mentioned, I agree this must be one the of Microsoft API.

For now, I have two devices (workstation and tablet) and the situation is happening in the tablet only. Currently, is very hard to find the root cause. If you have any suggestion, for example, an update for the required Microsoft API libraries, please, let me know to give a try.

In other hand, another issue I'm having (not related with this) is about using the library with [Fody](https://github.com/Fody/Costura). In order to avoid to deploy many libraries, I'm integrating all the libraries to the main .exe application. All the libraries (managed and native) has been integrated with success. However, I still need to place the ScreenRecorderLib.dll in same folder as the main app (exe) to avoid the following message.

The application start/loads with success. This exception happens when the record is enabled (press button). 

![image](https://user-images.githubusercontent.com/36808114/91055420-edbcb580-e624-11ea-8ff4-7972080ccbc6.png)

Please, may you have any suggestion regarding this situation?

**Comment by hulaomr** [comment]
I was evaluating the differences between the two devices and I found out the **display scale** was the critical point. The following videos show both test cases.

With the scale in 100%, the library and application work as expected.

![screenrecorder-100](https://user-images.githubusercontent.com/36808114/91078088-6a11c180-e642-11ea-85f8-9e88539324f4.gif)

With the **scale in 125%**, the situation reported in the first post is present:

- The application change the size automatically after press the button start
- The API used by ScreenRecorderLib change the application settings (Override high DPI scaling...)

![screenrecorder-125](https://user-images.githubusercontent.com/36808114/91078099-6f6f0c00-e642-11ea-9719-512243a0f6c6.gif)

Attached below is the solution (from **master**) plus the **test winform application** used in the previous test cases.

[ScreenRecorderLib-winform.zip](https://github.com/sskodje/ScreenRecorderLib/files/5119414/ScreenRecorderLib-winform.zip)

Hope this can help to understand the situation.

Thanks

**Comment by sskodje** [comment]
It is the call to IDXGIOutput1::DuplicateOutput that automatically enables "DPI aware" for the application. I don't know why. But you probably should make your application DPI aware anyway, so it does not appear blurry on higher DPI.
