### ISSUE TITLE
Quality Setting has no affect

### ISSUE THREAD

**Issue by jterrypsi** [sskodje/ScreenRecorderLib#87]
Hi, 

First off, this is a great library! It was really easy to get started and does exactly what I need! 

The only issue is that quality doesn't seem to change. I've set the BitrateMode to Quality, then set the Quality value to 1, 10, 50, 70 and it doesn't seem to have an affect.

My goal is to try and reduce file size a bit.

**Comment by sskodje** [comment]
This means the video encoder doesn't work as it should. If the quality setting works with hardware encoding disabled, try update or reinstall your graphics drivers. These bugs unfortunately pop up, as it's the responsibility of the graphics vendor to supply windows with the hardware video encoder, so AMD, NVidia, Intel, etc.
