### ISSUE TITLE
Unable to record mic

### ISSUE THREAD

**Issue by Buildex** [sskodje/ScreenRecorderLib#90]
I'm unable to record my mic. Can you guys test it so I know if I am the problem ?

**Comment by sskodje** [comment]
What kind of microphone are you using? It's working on my end.

**Comment by Buildex** [comment]
I have a XLR microphone hooked in a usb audio interface. (this kind of interface: https://www.behringer.com/product.html?modelCode=P0AVV)

And Ive tried switching device, but it doesnt work either.

**Comment by sskodje** [comment]
I'd appreciate it if you could log to a file with Trace level while trying to record with sound and attach it here. RecorderOptions->LogSeverityLevel and RecorderOptions->LogFilePath.

**Comment by Buildex** [comment]
Here it is : [https://pastebin.com/mBfYwZ5E](url)

**Comment by Buildex** [comment]
Did you find something ? It really doesn't work on my end

**Comment by FoxPride** [comment]
Check out this [commit ](https://github.com/sskodje/ScreenRecorderLib/commit/9304feefed65e633afd4de557076bc8d0630a56f) @Buildex

**Comment by Buildex** [comment]
> Check out this [commit ](https://github.com/sskodje/ScreenRecorderLib/commit/9304feefed65e633afd4de557076bc8d0630a56f) @Buildex

how do I get thoses changes ?

**Comment by FoxPride** [comment]
Grab latest release from repository of via [NuGet](https://www.nuget.org/packages/ScreenRecorderLib/)

**Comment by Buildex** [comment]
I am really dumb xD I forgot to enable IsInputDeviceEnabled. But thanks :)
