### ISSUE TITLE
Problem with garbage collection

### ISSUE THREAD

**Issue by qLlirik** [sskodje/ScreenRecorderLib#91]
We are using this dev tool for recording execution of our tests. But we catch error after 5 completed tests:

"The active test run was aborted. Reason: Test host process crashed : Process terminated. A callback was made on a garbage collected delegate of type 'ScreenRecorderLib!InternalStatusCallbackDelegate::Invoke'."

We create one instance of Recorder and use it in all tests executions. Do you have any ideas how it fix?

**Comment by sskodje** [comment]
This probably means that at some point, your instance of Recorder is going out of scope and is garbage collected. I would make sure that it has a fixed reference the whole time it is in use.

**Comment by qLlirik** [comment]
What you mean by " it has a fixed reference the whole time it is in use"? Make recorder static?

**Comment by sskodje** [comment]
Making a static reference would certainly prevent garbage collection, but you just need to prevent your reference from going out of scope. Make sure it's not held by a weakreference or something, or make sure that your method where the recorder instance is defined does not exit before the recording has ended. Can you give me a brief example of your code?

**Comment by qLlirik** [comment]
I rewrote code by use ScreenRecroderLib and all it's work. I don't know how.
