### ISSUE TITLE
No image when recording with HDR activated

### ISSUE THREAD

**Issue by hakito** [sskodje/ScreenRecorderLib#96]
When recording with HDR activated in windows settings, the recorded results in a plain black image.

At a first glance it seems the problem is root cause is from 
https://github.com/sskodje/ScreenRecorderLib/blob/23586a8f0075c2bd405a51aefeb37cdf4402fbb3/ScreenRecorderLib/internal_recorder.cpp#L1171 which is used for sourceFrameDesc
https://github.com/sskodje/ScreenRecorderLib/blob/23586a8f0075c2bd405a51aefeb37cdf4402fbb3/ScreenRecorderLib/internal_recorder.cpp#L1016

According to [MSDN](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_2/nf-dxgi1_2-idxgioutputduplication-getdesc?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(ATLCOMCLI%252FATL%253A%253A_NoAddRefReleaseOnCComPtr%253A%253AGetDesc);k(ATL%253A%253A_NoAddRefReleaseOnCComPtr%253A%253AGetDesc);k(DXGI1_2%252FIDXGIOutputDuplication%253A%253AGetDesc);k(IDXGIOutputDuplication%253A%253AGetDesc);k(GetDesc);k(TargetFrameworkMoniker-.NETFramework,Version%253Dv4.5.2);k(TargetFrameworkMoniker-.NETFramework,Version%253Dv4.5.2);k(DevLang-C%252B%252B);k(TargetOS-Windows);k(TargetFrameworkMoniker-.NETFramework,Version%253Dv4.5.2)%26rd%3Dtrue) this is always DXGI_FORMAT_B8G8R8A8_UNORM. But **that's wrong**. The interface returns a DXGI_FORMAT_R16G16B16A16_FLOAT on my HDR screen. But the _pDesktopResource_ from _AcquireNextFrame()_ is again in non HDR format. Another MSDN page also states[ it's always DXGI_FORMAT_B8G8R8A8_UNORM](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_2/nn-dxgi1_2-idxgioutputduplication).

**Comment by sskodje** [comment]
Interesting. Thanks for the PR! Looks like the documentation is indeed wrong, but i think it's even more wrong than this!

I tested on a HDR screen, and some frames come out as DXGI_FORMAT_R16G16B16A16_FLOAT, while others is DXGI_FORMAT_B8G8R8A8_UNORM. I'm going to do  more testing, but i think the description needs to be read on a frame-by-frame basis, since apparently they are not consistent at all.

**Comment by sskodje** [comment]
Do you only get DXGI_FORMAT_B8G8R8A8_UNORM on your textures when in HDR mode, or do you also get both types?

**Comment by hakito** [comment]
I updated the PR to log the current frame format at trace level.  I ran a 10 min recording at 60 fps. Indeed i got a single frame in a different format (10):

```
2020-10-15 08:26:25.036 [TRACE] [internal_recorder.cpp(operator ():735)] >> Current frame format: 87
2020-10-15 08:26:25.067 [TRACE] [internal_recorder.cpp(operator ():735)] >> Current frame format: 10
```

Very strange!

**Comment by sskodje** [comment]
Yeah i also got 87 (DXGI_FORMAT_B8G8R8A8_UNORM) and 10 (DXGI_FORMAT_R16G16B16A16_FLOAT). I can't find anything documented about this.

**Comment by hakito** [comment]
Probably this is already done in [CopyResource](https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11devicecontext-copyresource?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(D3D11%252FID3D11DeviceContext%253A%253ACopyResource);k(ID3D11DeviceContext%253A%253ACopyResource);k(CopyResource);k(TargetFrameworkMoniker-.NETFramework,Version%253Dv4.5.2);k(TargetFrameworkMoniker-.NETFramework,Version%253Dv4.5.2);k(DevLang-C%252B%252B);k(TargetOS-Windows);k(TargetFrameworkMoniker-.NETFramework,Version%253Dv4.5.2)%26rd%3Dtrue#remarks)? Unfortunately the link in the remarks section regarding conversion also seems outdated. But [Data Conversion Rules](https://docs.microsoft.com/en-us/windows/win32/direct3d10/d3d10-graphics-programming-guide-resources-data-conversion#conververting-from-a-higher-range-representation-to-a-lower-range-representation) indicate that a conversion should be possible?

Actually I think by pinning the _sourceFrameDesc_ to DXGI_FORMAT_B8G8R8A8_UNORM the line https://github.com/sskodje/ScreenRecorderLib/blob/fa1348a79ce7df23093ceb94b8a1a25b40d94ead/ScreenRecorderLib/internal_recorder.cpp#L737
already does the nescessary conversion. At least my screen recording was not broken.

Did you have a broken video when _pAcquiredDesktopImage_ was in HDR format?

**Comment by sskodje** [comment]
Yes. Every time a frame was in format 10 (DXGI_FORMAT_R16G16B16A16_FLOAT), the encoder gave an error and that part of the video was black. This is probably due to differences in encoders. My PC has AMD graphics, while i'm guessing you use either Intel or Nvidia.

**Comment by hakito** [comment]
Yes, I have a nvidia card. If the amount different frames is neglible the _invalid_ frames could be skipped instead of converted. If this causes serious problems on some systems, conversion can still be added later. What do you think?

**Comment by hakito** [comment]
Great, when do you plan the next release?
