### ISSUE TITLE
Black screen while recording.

### ISSUE THREAD

**Issue by qLlirik** [sskodje/ScreenRecorderLib#98]
I recorded some videos during 2-4 minutes. There is appears black screen in the last half. It's appears for a 5-15 seconds and disappears.

Why it's happens, what do you think?

**Comment by FoxPride** [comment]
@qLlirik read this [section](https://github.com/sskodje/ScreenRecorderLib/commit/8fe565a96b532287ab5c4c331c90f7b3e41ec8be#comments)

**Comment by qLlirik** [comment]
@FoxPride, it's happens for unchangeable screen, i'm right understood you?

**Comment by FoxPride** [comment]
Yes. You are right. Comment code as in this [message ](https://github.com/sskodje/ScreenRecorderLib/commit/8fe565a96b532287ab5c4c331c90f7b3e41ec8be#commitcomment-43204010) inside the **if** block

**Comment by qLlirik** [comment]
@FoxPride, can I catch this moment when black screen appears and pause screen recording?

**Comment by FoxPride** [comment]
I guess you can. Modify code inside block to pause video instead of inserting black screen.

**Comment by qLlirik** [comment]
@FoxPride, thanks for you quickly answer.

**Comment by sskodje** [comment]
This was an uninteded side effect of a change in version 2.6, but it is fixed with version 2.8 that i pushed yesterday.
